"""
Rich Activity Studio content for GenAI Executive Management Studio.
Classroom-ready synthetic activities; no external API required.
"""

ACTIVITY_MODES = [
    "Instructor Demo Mode",
    "Learner Practice Mode",
    "Weak vs Strong Prompt Mode",
    "Group Discussion Mode",
    "Reflection Mode",
]

ACTIVITY_STUDIO = {
    "Raw Note to Executive Brief": {
        "duration": "25 min",
        "activity_type": "Guided practice",
        "mode": "Individual",
        "objective": "Convert an unstructured administrative note into a leadership-ready executive brief.",
        "business_context": "A programme head needs a concise decision brief on training attendance and reporting efficiency. The source note is incomplete and informal, so learners must design a prompt that asks for structure, evidence limits, decision points, and follow-up actions.",
        "sample_input": "Attendance has been low. People are busy. We need to fix it. Some departments do not send nominations on time. Reports are delayed because sign-in sheets are manually consolidated. Leadership wants a better process before the next training cycle.",
        "instructions": "1. Show the raw training attendance note. 2. Ask learners to identify what structure is missing. 3. Have them build a prompt to convert the note. 4. Compare outputs across groups.",
        "steps": [
            {
                "title": "Step 1: Show Raw Note",
                "button_label": "Step 1: Show Raw Note",
                "instructor_action": "Display the raw note without explaining it first. Ask learners to read it as if they were preparing a note for senior leadership.",
                "learner_task": "Identify what information is visible, what is vague, and what cannot be assumed.",
                "facilitator_script": "This is a realistic raw note: short, informal, and operationally useful, but not leadership-ready. What would make it unsafe to forward as it is?",
                "expected_response": "Learners should notice that the note lacks background, evidence, root causes, decision options, owners, and timelines.",
                "common_mistakes": "Treating the note as complete; inventing numbers; assuming reasons for low attendance; writing recommendations without constraints.",
                "teaching_takeaway": "AI can structure weak source material, but it cannot responsibly invent missing evidence."
            },
            {
                "title": "Step 2: Identify Missing Structure",
                "button_label": "Step 2: Identify Missing Structure",
                "instructor_action": "Ask learners to list missing sections before writing any prompt.",
                "learner_task": "Suggest headings required in a leadership brief.",
                "facilitator_script": "Before we prompt the AI, let us decide the structure we want. What sections would help a programme head make a decision?",
                "expected_response": "Background, key observations, likely causes, risks, decision points, recommended actions, owner/timeline, and uncertainties.",
                "common_mistakes": "Jumping directly to solutions; requesting a summary only; not asking the AI to mark uncertainty.",
                "teaching_takeaway": "A good prompt starts with the decision context, not with the AI tool."
            },
            {
                "title": "Step 3: Build the Prompt",
                "button_label": "Step 3: Build the Prompt",
                "instructor_action": "Have learners convert the missing structure into a strong prompt using Role, Context, Task, Output, Format, and Evaluation constraints.",
                "learner_task": "Create a prompt that asks for a concise brief and prevents unsupported claims.",
                "facilitator_script": "Let us add role, audience, format, and safety rule. The most important phrase here is: do not invent facts.",
                "expected_response": "A strong prompt with role, audience, structured sections, concise tone, uncertainty marking, and no-invention rule.",
                "common_mistakes": "Using vague verbs such as 'improve this'; asking for too many outputs; forgetting format and verification rules.",
                "teaching_takeaway": "Prompt quality determines whether the output becomes a usable management document or a generic paragraph."
            },
            {
                "title": "Step 4: Compare Outputs",
                "button_label": "Step 4: Compare Outputs",
                "instructor_action": "Compare weak, improved, and strong prompts. Ask learners which output would be safest for leadership use.",
                "learner_task": "Evaluate completeness, factual discipline, actionability, and tone.",
                "facilitator_script": "Which version would you circulate after human review? Which version creates the greatest risk of overclaiming?",
                "expected_response": "The strong prompt should produce a structured brief with clear caveats and decision points.",
                "common_mistakes": "Preferring the longest output; ignoring unsupported claims; not checking whether recommendations follow from the source note.",
                "teaching_takeaway": "The best AI-assisted output is not the most fluent one; it is the most useful, bounded, and verifiable one."
            }
        ],
        "weak_prompt": "Summarise this attendance issue.",
        "improved_prompt": "Read the following training attendance note and summarise the problem, likely reasons, and suggested next steps for a programme head.",
        "strong_prompt": "Act as an executive assistant supporting a senior programme head. Read the following training attendance note and prepare a concise leadership brief with background, key observations, likely root causes, decision points, recommended actions, risks, and a follow-up timeline. Clearly mark uncertain points and do not invent data beyond the note.",
        "why_weak": "It gives no role, audience, structure, evidence boundary, or decision purpose. The output will likely be generic and may invent missing details.",
        "why_strong": "It defines the role, audience, structure, decision use, uncertainty handling, and factual boundary.",
        "expected_output_structure": "Background; Key Observations; Possible Root Causes; Decision Points; Risks; Recommended Actions; Follow-up Timeline; Items Requiring Verification.",
        "ideal_output": "A leadership-ready brief should state that attendance is low, nomination delays and manual consolidation appear to affect reporting, and leadership needs a standard process before the next cycle. It should recommend a nomination tracker, clear confirmation timeline, standard attendance categories, and a single reporting template, while marking missing evidence such as exact attendance rate, affected departments, and cost of delay.",
        "common_mistakes": ["Inventing attendance percentages", "Writing a complaint instead of a brief", "Ignoring reporting delay", "Not separating facts from assumptions", "Missing decision points"],
        "discussion_questions": ["What facts are available?", "What facts are missing?", "Which recommendation can be made safely?", "What should a human verify before circulation?"],
        "debrief_question": "Which parts of the AI output would need human verification before the brief is circulated to leadership?",
        "debrief_answer": "Attendance figures, department names, causes of non-attendance, exact reporting delay, ownership of follow-up actions, and any timeline or policy commitment must be verified before circulation.",
        "instructor_notes": "This is a good first activity because it shows the difference between summarisation and management briefing. Keep the discussion focused on evidence discipline.",
        "key_takeaway": "A strong management prompt converts raw notes into structured judgment support while preserving human accountability.",
        "extension_activity": "Ask learners to add a risk table and a 48-hour action plan to the prompt."
    },
    "Weak vs Strong Prompt": {
        "duration": "10 min",
        "activity_type": "Comparison",
        "mode": "Full class",
        "objective": "Understand how prompt specificity improves AI output quality.",
        "business_context": "Managers often begin with short prompts that produce generic responses. This activity helps learners see how role, context, task, output format, and constraints change the usefulness of AI-generated work.",
        "sample_input": "The team needs to summarise a short operational note for leadership. The note may contain incomplete facts and should not be overinterpreted.",
        "instructions": "1. Show the weak prompt on screen. 2. Ask learners what is missing. 3. Build the strong prompt together using selections. 4. Discuss the difference in expected output quality.",
        "steps": [
            {"title": "Step 1: Show Weak Prompt", "button_label": "Step 1: Show Weak Prompt", "instructor_action": "Display the weak prompt without explanation.", "learner_task": "Point out what the prompt fails to specify.", "facilitator_script": "Would this prompt produce something usable for leadership? Why or why not?", "expected_response": "It lacks audience, structure, tone, constraints, and verification rules.", "common_mistakes": "Saying the prompt is fine because it is short.", "teaching_takeaway": "Short prompts are not always efficient; they often shift work to the reviewer."},
            {"title": "Step 2: Add Missing Elements", "button_label": "Step 2: Add Missing Elements", "instructor_action": "Ask learners to suggest role, audience, output, and format.", "learner_task": "Convert missing elements into prompt language.", "facilitator_script": "Let us add one improvement at a time. What role should the AI play? Who is the output for?", "expected_response": "Learners add executive assistant, senior leadership, 150 words, sections, and no unsupported facts.", "common_mistakes": "Adding too much context but no output format.", "teaching_takeaway": "The prompt should reduce ambiguity for the model."},
            {"title": "Step 3: Compare Strong Prompt", "button_label": "Step 3: Compare Strong Prompt", "instructor_action": "Reveal the strong prompt and ask learners to compare.", "learner_task": "Identify which R-C-T-O-F-E elements are present.", "facilitator_script": "This version is longer, but is it more controlled?", "expected_response": "Learners should identify role, context, task, output, format, and evaluation rule.", "common_mistakes": "Thinking a longer prompt is automatically better.", "teaching_takeaway": "Length helps only when every sentence adds control or clarity."},
            {"title": "Step 4: Predict Output Quality", "button_label": "Step 4: Predict Output Quality", "instructor_action": "Ask learners to predict differences in output.", "learner_task": "State expected differences before testing.", "facilitator_script": "Before running anything, what do you expect the AI to do differently?", "expected_response": "The strong prompt should be structured, concise, decision-oriented, and safer.", "common_mistakes": "Focusing only on grammar and not on decision usefulness.", "teaching_takeaway": "Prompt design is a managerial control mechanism."}
        ],
        "weak_prompt": "Summarise this.",
        "improved_prompt": "Summarise the following note for senior leadership in a clear and professional tone.",
        "strong_prompt": "Act as an executive assistant. Summarise the following note for senior leadership in 150 words. Include background, key observations, decision points, and recommended next steps. Do not add unsupported information and mark any missing details that require verification.",
        "why_weak": "The AI has no clue about audience, purpose, structure, length, or evidence limits.",
        "why_strong": "The strong version tells the AI who it is, who will read the output, what sections to include, and how to handle missing information.",
        "expected_output_structure": "150-word leadership summary with background, key observations, decision points, next steps, and verification notes.",
        "ideal_output": "The ideal output is concise, structured, and cautious. It should not add facts that are not present in the source note.",
        "common_mistakes": ["Only improving grammar", "Not naming the audience", "Forgetting the output format", "Not adding evidence limits"],
        "discussion_questions": ["Which word in the strong prompt most improves safety?", "What would happen if we removed the audience?", "How could the prompt be shortened without losing quality?"],
        "debrief_question": "What specifically makes the strong prompt more likely to produce a useful output?",
        "debrief_answer": "It reduces ambiguity by specifying role, audience, structure, length, tone, and verification expectations.",
        "instructor_notes": "Use this as a quick opening demonstration before detailed activities.",
        "key_takeaway": "A strong prompt is a compact management specification.",
        "extension_activity": "Ask learners to create a strong prompt in exactly 60 words."
    },
    "Meeting Notes to Action Tracker": {
        "duration": "20 min",
        "activity_type": "Documentation practice",
        "mode": "Pairs",
        "objective": "Convert raw meeting notes into a clear action tracker with owners, deadlines, and pending decisions.",
        "business_context": "Management meetings often produce long notes but weak accountability. This activity teaches learners to prompt AI for structured action tracking without inventing missing owners or dates.",
        "sample_input": "Meeting: Dashboard rollout coordination. Pilot dashboard will go live for three departments on 20 April. User access list must be frozen by 12 April. Two departments have not submitted KPI definitions. Finance asked whether maintenance cost is in the approved budget. Coordinators requested a short training video. Project Lead agreed to prepare a one-page colour-code guide. No final decision on dashboard maintenance after pilot.",
        "instructions": "1. Present raw meeting notes. 2. Ask learners to identify decisions, actions, owners, and open issues. 3. Build an action-tracker prompt. 4. Reveal the model tracker.",
        "steps": [
            {"title": "Step 1: Separate Notes", "button_label": "Step 1: Separate Notes", "instructor_action": "Ask learners to split the note into decisions, action items, and open issues.", "learner_task": "Mark each sentence as decision, action, context, or pending issue.", "facilitator_script": "Not every meeting sentence is an action. Let us classify before asking AI to format it.", "expected_response": "Learners identify pilot date as decision, access list/KPI definitions/guide as actions, maintenance ownership as open issue.", "common_mistakes": "Treating all discussion points as action items.", "teaching_takeaway": "Classification improves action tracking."},
            {"title": "Step 2: Define Tracker Columns", "button_label": "Step 2: Define Tracker Columns", "instructor_action": "Ask which columns are needed.", "learner_task": "Propose action item, owner, deadline, status, dependency, and remarks.", "facilitator_script": "A tracker is useful only when every row can be followed up.", "expected_response": "Columns include owner and due date, with blank/uncertain values marked.", "common_mistakes": "Forcing unknown owners or dates.", "teaching_takeaway": "Unknowns should be labelled, not guessed."},
            {"title": "Step 3: Build Prompt", "button_label": "Step 3: Build Prompt", "instructor_action": "Guide learners to write a prompt that forbids invented owners/dates.", "learner_task": "Write a prompt for table output and pending issues.", "facilitator_script": "The most important instruction: mark missing owners or deadlines as 'to be confirmed'.", "expected_response": "Prompt asks for a tracker table, decisions list, pending issues, and verification notes.", "common_mistakes": "Not requesting pending decisions.", "teaching_takeaway": "A good prompt protects governance records."},
            {"title": "Step 4: Review Tracker", "button_label": "Step 4: Review Tracker", "instructor_action": "Reveal model answer and ask learners what still needs human follow-up.", "learner_task": "Identify missing owners, dates, and dependencies.", "facilitator_script": "Which row would you follow up first tomorrow morning?", "expected_response": "KPI definitions and access list are urgent because they affect launch readiness.", "common_mistakes": "Overlooking the pending maintenance decision.", "teaching_takeaway": "Meeting summaries should create accountability, not just documentation."}
        ],
        "weak_prompt": "Make meeting minutes from this.",
        "improved_prompt": "Turn the meeting notes into minutes with decisions and actions.",
        "strong_prompt": "Act as a project coordination officer. Convert the following raw meeting notes into an action tracker. Include decisions, action item, owner, deadline, dependency, status, and open issues. If an owner or deadline is missing, write 'To be confirmed' rather than inventing it.",
        "why_weak": "It asks for minutes but not for actionable follow-up.",
        "why_strong": "It specifies the table structure and explicitly prevents invented accountability details.",
        "expected_output_structure": "Meeting summary; Decisions; Action tracker table; Open issues; Verification required.",
        "ideal_output": "The action tracker should include KPI definitions due 10 April, access list by 12 April, one-page guide by 16 April, budget clarification by Finance, and unresolved dashboard maintenance ownership.",
        "common_mistakes": ["Inventing owners", "Missing unresolved issues", "Ignoring dependencies", "Writing narrative only"],
        "discussion_questions": ["Which action is most time-critical?", "What details are missing?", "How should unresolved issues be escalated?"],
        "debrief_question": "What makes an AI-generated action tracker unsafe if used without review?",
        "debrief_answer": "It may invent owners, deadlines, decisions, or status. Human review must verify accountability details.",
        "instructor_notes": "Useful for showing the difference between summarisation and operational accountability.",
        "key_takeaway": "A meeting-note prompt should produce follow-up clarity, not just a polished record.",
        "extension_activity": "Ask learners to add RAG status and escalation triggers."
    },
    "Delay Report to Root-Cause Brief": {
        "duration": "20 min",
        "activity_type": "Root-cause analysis",
        "mode": "Small groups",
        "objective": "Transform a delay report into a concise root-cause and mitigation brief.",
        "business_context": "A service centre upgrade is delayed because equipment delivery was incomplete and coordination among vendor, transporter, and installation team was weak. Learners must distinguish symptoms from causes.",
        "sample_input": "Original delivery commitment was 15 April; revised delivery is 24 April. Partial shipment reached regional hub; 8 desktop systems and 4 scanners were missing. Vendor confirmed missing items were held back due to packaging mismatch. Installation at Centre A is 60% complete; Centres B and C have not started. Staff training scheduled for 22 April may need rescheduling. Vendor and local project team used separate tracking sheets.",
        "instructions": "1. Show the delay report. 2. Ask groups to identify symptoms, likely root causes, impact, and short-term mitigations. 3. Compare weak and strong prompts. 4. Reveal a management brief.",
        "steps": [
            {"title": "Step 1: Read Delay Facts", "button_label": "Step 1: Read Delay Facts", "instructor_action": "Ask learners to underline facts only.", "learner_task": "Separate timeline facts from interpretations.", "facilitator_script": "What do we know for sure from the report?", "expected_response": "Known facts include dates, missing items, partial installation, training risk, separate trackers.", "common_mistakes": "Blaming the vendor without evidence.", "teaching_takeaway": "Root-cause work starts with fact discipline."},
            {"title": "Step 2: Identify Cause Categories", "button_label": "Step 2: Identify Cause Categories", "instructor_action": "Ask learners to group causes into process, communication, vendor, and planning.", "learner_task": "Map likely causes to categories.", "facilitator_script": "Which issues are operational symptoms and which are root causes?", "expected_response": "Packaging mismatch, checklist failure, tracking fragmentation, no contingency buffer, route communication gap.", "common_mistakes": "Listing impacts as causes.", "teaching_takeaway": "Cause categories prevent shallow analysis."},
            {"title": "Step 3: Draft Mitigations", "button_label": "Step 3: Draft Mitigations", "instructor_action": "Ask for short-term mitigations only.", "learner_task": "Recommend two immediate actions within constraints.", "facilitator_script": "We are not redesigning the vendor contract today. What can management do this week?", "expected_response": "Single tracker, daily dispatch/installation call, reschedule training, confirm replacement dispatch, install available equipment first.", "common_mistakes": "Suggesting long-term procurement changes despite constraint.", "teaching_takeaway": "Good prompts respect decision horizon."},
            {"title": "Step 4: Build Brief", "button_label": "Step 4: Build Brief", "instructor_action": "Reveal strong prompt and expected brief.", "learner_task": "Check whether the brief separates cause, impact, and action.", "facilitator_script": "A management brief should help action, not simply narrate delay.", "expected_response": "Concise brief with root causes, impacts, two mitigations, and verification items.", "common_mistakes": "Overloading the brief with too much timeline detail.", "teaching_takeaway": "Root-cause prompts should ask for causes, impacts, and next actions separately."}
        ],
        "weak_prompt": "Why is this delayed?",
        "improved_prompt": "Analyse this delay report and suggest actions.",
        "strong_prompt": "Act as a logistics analyst. Given the following delay report, identify the most likely root causes, separate symptoms from causes, assess short-term operational impact, and recommend two immediate mitigation actions. Do not recommend contract changes. Format as a concise management brief.",
        "why_weak": "It invites a generic answer and may jump to blame.",
        "why_strong": "It specifies analytical separation, impact horizon, mitigation count, and constraint.",
        "expected_output_structure": "Situation; Symptoms; Likely Root Causes; Short-term Impact; Two Mitigation Actions; Verification Needed.",
        "ideal_output": "Likely causes include weak dispatch checklist verification, packaging mismatch, fragmented tracking, route communication gap, and insufficient buffer before training. Immediate actions: create a single tracker with daily owner review; resequence installation and training based on confirmed replacement dispatch.",
        "common_mistakes": ["Confusing symptoms with causes", "Ignoring constraints", "Suggesting too many actions", "Assigning blame without evidence"],
        "discussion_questions": ["What is the root cause?", "What is only a symptom?", "Which action can be done this week?"],
        "debrief_question": "How can a prompt prevent AI from turning a delay report into unsupported blame?",
        "debrief_answer": "By asking the AI to separate known facts, likely causes, impacts, assumptions, and verification needs.",
        "instructor_notes": "Excellent for operations and logistics learners; emphasize evidence and short-term decision horizon.",
        "key_takeaway": "A strong root-cause prompt narrows the decision horizon and reduces unsupported blame.",
        "extension_activity": "Ask learners to convert the mitigation actions into a 3-day action tracker."
    },
    "Customer Complaint to Service Recovery Plan": {
        "duration": "18 min",
        "activity_type": "Service recovery",
        "mode": "Pairs",
        "objective": "Convert customer feedback into a respectful recovery plan and communication draft.",
        "business_context": "A customer has escalated a poor service experience. Managers must respond empathetically while also recommending process improvements.",
        "sample_input": "A priority customer reported that delivery was delayed by two days, the support desk gave different answers on three calls, and the final status update arrived after the issue was resolved. The customer is frustrated because the order was needed for a scheduled event. The account team wants a recovery plan and a draft apology email.",
        "instructions": "1. Show the complaint. 2. Ask learners to separate emotion, facts, and service failure. 3. Build a prompt for recovery plan and communication. 4. Reveal suggested response.",
        "steps": [
            {"title": "Step 1: Read Customer Voice", "button_label": "Step 1: Read Customer Voice", "instructor_action": "Ask learners to identify what the customer experienced.", "learner_task": "Separate emotional impact from operational facts.", "facilitator_script": "What is the customer really upset about: only delay, or also communication?", "expected_response": "Delay, inconsistent answers, late update, event dependency, loss of confidence.", "common_mistakes": "Treating it as only a logistics problem.", "teaching_takeaway": "Service recovery addresses both operational failure and trust damage."},
            {"title": "Step 2: Identify Recovery Needs", "button_label": "Step 2: Identify Recovery Needs", "instructor_action": "Ask what a recovery plan should include.", "learner_task": "Suggest immediate response, corrective action, owner, timeline, and prevention step.", "facilitator_script": "A good apology without process correction is incomplete.", "expected_response": "Acknowledge issue, clarify facts, assign owner, update protocol, prevent inconsistent communication.", "common_mistakes": "Overpromising compensation or blaming staff.", "teaching_takeaway": "Tone and process both matter."},
            {"title": "Step 3: Build Prompt", "button_label": "Step 3: Build Prompt", "instructor_action": "Guide learners to ask for two outputs: recovery plan and customer email.", "learner_task": "Create prompt with respectful tone and no admission beyond known facts.", "facilitator_script": "What tone should this use? What should it avoid?", "expected_response": "Professional, empathetic, accountable, specific, not defensive.", "common_mistakes": "Using exaggerated apology or legal admission.", "teaching_takeaway": "Prompt tone controls relationship risk."},
            {"title": "Step 4: Review Response", "button_label": "Step 4: Review Response", "instructor_action": "Reveal model answer and ask what a manager should verify.", "learner_task": "Identify facts and commitments requiring approval.", "facilitator_script": "What would you check before sending this email?", "expected_response": "Delivery facts, compensation approval, owner, revised communication protocol.", "common_mistakes": "Sending AI draft without verifying timeline.", "teaching_takeaway": "AI can draft empathy; managers must verify commitments."}
        ],
        "weak_prompt": "Reply to this customer complaint.",
        "improved_prompt": "Write a polite apology and suggest how to handle this complaint.",
        "strong_prompt": "Act as a service recovery manager. Read the following customer complaint and produce two outputs: a short internal recovery plan and a respectful customer response email. Acknowledge known facts, avoid unsupported admissions, specify immediate actions, and mark any commitment that requires managerial approval.",
        "why_weak": "It focuses only on a reply and misses internal recovery actions and approval risks.",
        "why_strong": "It separates internal action from external communication and controls tone, facts, and approval boundaries.",
        "expected_output_structure": "Issue summary; Recovery plan; Prevention action; Draft customer email; Verification/approval checklist.",
        "ideal_output": "The plan should acknowledge delayed delivery and inconsistent communication, assign a single account owner, provide a verified status explanation, review support scripts, and send a concise apology with clear next steps.",
        "common_mistakes": ["Over-apologising without action", "Inventing compensation", "Blaming individuals", "Ignoring inconsistent communication"],
        "discussion_questions": ["What should be said to the customer?", "What should remain internal?", "Which commitments need approval?"],
        "debrief_question": "Why should customer-facing AI drafts be reviewed carefully?",
        "debrief_answer": "They may create unintended promises, admissions, or tone problems if not verified and approved.",
        "instructor_notes": "Useful to discuss empathy, accountability, and escalation control.",
        "key_takeaway": "Good service recovery combines empathy with operational correction.",
        "extension_activity": "Ask learners to create a one-call update script for the support desk."
    },
    "Training Attendance Note to Decision Brief": {
        "duration": "20 min",
        "activity_type": "Decision briefing",
        "mode": "Individual",
        "objective": "Turn attendance observations into a decision-oriented management note.",
        "business_context": "Training attendance is below target and reporting is delayed. Leadership must decide whether to change nomination tracking and communication rules.",
        "sample_input": "Average attendance across internal training sessions has been 68% against a desired 85%. Participants cite scheduling conflicts, late final dates, and uncertainty about whether sessions are mandatory. Attendance is compiled manually from sign-in sheets, and programme heads receive reports 5-7 working days after sessions.",
        "instructions": "1. Show attendance note. 2. Ask learners what decision is required. 3. Build a decision-brief prompt. 4. Reveal model structure.",
        "steps": [
            {"title": "Step 1: Spot Decision Need", "button_label": "Step 1: Spot Decision Need", "instructor_action": "Ask learners what leadership must decide.", "learner_task": "State the decision question.", "facilitator_script": "This is not only a low-attendance problem. What decision does it require?", "expected_response": "Whether to introduce standard tracker, confirmation rule, and reporting template.", "common_mistakes": "Recommending training reminders only.", "teaching_takeaway": "Briefs must surface decisions, not only describe problems."},
            {"title": "Step 2: Extract Evidence", "button_label": "Step 2: Extract Evidence", "instructor_action": "Ask learners to list measurable evidence.", "learner_task": "Identify attendance gap, reasons, and reporting delay.", "facilitator_script": "Which numbers are available and which are missing?", "expected_response": "68%, 85%, reasons, 5-7 days report delay; exact department-wise data missing.", "common_mistakes": "Inventing department-specific rates.", "teaching_takeaway": "Use available evidence without filling gaps."},
            {"title": "Step 3: Build Options", "button_label": "Step 3: Build Options", "instructor_action": "Ask learners to request options, pros/cons, and recommendation.", "learner_task": "Design prompt for decision options.", "facilitator_script": "Leadership often needs options, not a single command.", "expected_response": "Options include current process, tracker, or form-linked dashboard.", "common_mistakes": "Giving only one solution.", "teaching_takeaway": "Decision briefs are stronger when options are compared."},
            {"title": "Step 4: Human Review", "button_label": "Step 4: Human Review", "instructor_action": "Ask what needs verification before official use.", "learner_task": "Mark assumptions and missing evidence.", "facilitator_script": "What would you verify before this goes to the programme head?", "expected_response": "Attendance source, reasons from feedback, feasibility of tracker, owner responsibilities.", "common_mistakes": "Treating AI options as final decisions.", "teaching_takeaway": "AI supports decision preparation; humans own decisions."}
        ],
        "weak_prompt": "Fix this training attendance problem.",
        "improved_prompt": "Prepare a decision note on low training attendance and reporting delay.",
        "strong_prompt": "Act as a senior programme analyst. Prepare a decision brief from the following attendance note. Include background, evidence, causes stated in the note, decision options, risks, recommended action, implementation timeline, and verification needed. Do not invent department-level data.",
        "why_weak": "It assumes the AI can solve the problem without evidence or decision constraints.",
        "why_strong": "It asks for options and boundaries, while preventing invented department data.",
        "expected_output_structure": "Background; Evidence; Stated Causes; Options; Risks; Recommendation; Timeline; Verification.",
        "ideal_output": "The brief should recommend a standard nomination tracker, 48-hour confirmation rule, and common reporting template, while noting that department-level attendance and mandatory/optional classification need verification.",
        "common_mistakes": ["Ignoring reporting delay", "Suggesting penalties immediately", "Inventing survey data", "Missing decision options"],
        "discussion_questions": ["What is the real decision?", "Which option is low-cost?", "What would be difficult to implement?"],
        "debrief_question": "What should leadership verify before changing the attendance process?",
        "debrief_answer": "Accuracy of attendance data, participant feedback categories, department coordinator workload, and feasibility of the tracker or form-based system.",
        "instructor_notes": "Good activity for showing decision-oriented writing.",
        "key_takeaway": "A decision brief should connect evidence to options and action.",
        "extension_activity": "Ask learners to build a risk table for each decision option."
    },
    "Policy Text to Manager-Friendly Summary": {
        "duration": "18 min",
        "activity_type": "Policy simplification",
        "mode": "Individual",
        "objective": "Simplify policy language without changing meaning or weakening compliance.",
        "business_context": "Managers need to understand digital tool usage rules quickly, but official policy language is dense. The task is to create a plain-language summary with do/don't guidance.",
        "sample_input": "Employees may use approved digital tools for drafting, summarisation, scheduling, training preparation, and non-sensitive analysis. Confidential, personally identifiable, financial, legal, disciplinary, medical, procurement-sensitive, or unpublished strategic information must not be entered into public AI tools unless formal approval is granted. AI-assisted outputs used officially must be reviewed by the responsible officer.",
        "instructions": "1. Show policy text. 2. Ask learners what must not change. 3. Build simplification prompt. 4. Review for compliance risk.",
        "steps": [
            {"title": "Step 1: Identify Protected Meaning", "button_label": "Step 1: Identify Protected Meaning", "instructor_action": "Ask learners which clauses must be preserved exactly in meaning.", "learner_task": "Identify restrictions and accountability rules.", "facilitator_script": "Plain language should not make policy weaker. What must stay firm?", "expected_response": "Sensitive data prohibition, formal approval, human review, accountability.", "common_mistakes": "Softening mandatory language.", "teaching_takeaway": "Simplification is not dilution."},
            {"title": "Step 2: Define Audience", "button_label": "Step 2: Define Audience", "instructor_action": "Ask who will read the summary.", "learner_task": "Define manager audience and practical format.", "facilitator_script": "A manager needs operational guidance, not legal commentary.", "expected_response": "Do/don't table, examples, escalation note.", "common_mistakes": "Writing another dense policy.", "teaching_takeaway": "Audience determines summary format."},
            {"title": "Step 3: Add Safety Check", "button_label": "Step 3: Add Safety Check", "instructor_action": "Ask learners to include a no-change-of-meaning constraint.", "learner_task": "Add 'preserve policy intent' to prompt.", "facilitator_script": "What instruction tells AI not to reinterpret the policy?", "expected_response": "Use 'do not add, remove, or weaken obligations'.", "common_mistakes": "Asking AI for legal interpretation.", "teaching_takeaway": "Policy prompts need scope limits."},
            {"title": "Step 4: Review Summary", "button_label": "Step 4: Review Summary", "instructor_action": "Reveal model answer and ask learners to check compliance.", "learner_task": "Flag any softened or unsupported statement.", "facilitator_script": "Would you allow this summary to be circulated? What needs review?", "expected_response": "Summary requires authorised policy review before official circulation.", "common_mistakes": "Skipping official review.", "teaching_takeaway": "AI can aid comprehension but not replace authorised interpretation."}
        ],
        "weak_prompt": "Make this policy simple.",
        "improved_prompt": "Summarise this policy for managers in simple language.",
        "strong_prompt": "Act as a policy communication specialist. Convert the following public policy text into a manager-friendly summary. Preserve the policy intent, do not add legal interpretation, include a do/don't table, examples of safe and unsafe use, and a note that official interpretation remains with authorised personnel.",
        "why_weak": "It may oversimplify or weaken compliance obligations.",
        "why_strong": "It protects policy meaning and specifies operational format and authority limits.",
        "expected_output_structure": "Plain-language summary; Do/Don't table; Safe examples; Unsafe examples; Escalation note; Verification reminder.",
        "ideal_output": "Managers may use AI for low-risk drafting and summarisation, but must not enter sensitive data into public tools. All official AI-assisted outputs require human review, and uncertain policy meanings require authorised clarification.",
        "common_mistakes": ["Weakening mandatory clauses", "Adding legal advice", "Not listing sensitive data categories", "Ignoring accountability"],
        "discussion_questions": ["What cannot be simplified?", "What examples help managers?", "Who should approve the summary?"],
        "debrief_question": "Why is policy simplification a medium-risk AI use case?",
        "debrief_answer": "AI may alter meaning or omit obligations, so human policy review is necessary.",
        "instructor_notes": "Use this to discuss responsible AI and compliance boundaries.",
        "key_takeaway": "Plain language must preserve obligations and accountability.",
        "extension_activity": "Ask learners to create a one-page policy checklist."
    },
    "Dashboard Summary to Leadership Narrative": {
        "duration": "20 min",
        "activity_type": "Data storytelling",
        "mode": "Individual",
        "objective": "Turn dashboard figures into a balanced executive narrative without overstating causality.",
        "business_context": "Service performance has improved in some areas but still misses targets. Learners must create a leadership narrative that separates improvement, concern, and action.",
        "sample_input": "Total service requests: 8,450; previous month: 7,980. Closure rate: 92%; target: 94%. Average resolution time: 39 hours; target: 36; previous month: 42. Escalation rate: 9.8%; target below 8%. Digital ticket submission: 81%; target 80%. Pending requests older than 5 days: 312; previous month: 355. Two regional teams account for 46% of old pending requests.",
        "instructions": "1. Show dashboard facts. 2. Ask learners to identify signals. 3. Build leadership narrative prompt. 4. Discuss what cannot be concluded.",
        "steps": [
            {"title": "Step 1: Identify Signals", "button_label": "Step 1: Identify Signals", "instructor_action": "Ask learners to mark green, amber, and red signals.", "learner_task": "Classify improvements, missed targets, and focus areas.", "facilitator_script": "Which numbers improved, and which still need attention?", "expected_response": "Digital adoption and backlog improved; closure rate/resolution time/escalations still need attention.", "common_mistakes": "Calling all improvements success without targets.", "teaching_takeaway": "Narratives must compare against both previous period and target."},
            {"title": "Step 2: Avoid Overclaiming", "button_label": "Step 2: Avoid Overclaiming", "instructor_action": "Ask learners what cannot be concluded.", "learner_task": "List causal claims that are unsupported.", "facilitator_script": "Can we say digital tickets caused faster resolution? What evidence would we need?", "expected_response": "No causality can be claimed without more analysis.", "common_mistakes": "Overstating causality from correlation.", "teaching_takeaway": "Good data storytelling is disciplined storytelling."},
            {"title": "Step 3: Build Prompt", "button_label": "Step 3: Build Prompt", "instructor_action": "Guide prompt for concise narrative and leadership action.", "learner_task": "Request highlights, concerns, action needed, and caveats.", "facilitator_script": "Leadership needs meaning, not a repetition of every number.", "expected_response": "Prompt asks for 3 highlights, 3 concerns, 2 actions, and caveats.", "common_mistakes": "Pasting all metrics with no interpretation.", "teaching_takeaway": "AI can help convert metrics into decision narrative."},
            {"title": "Step 4: Review Narrative", "button_label": "Step 4: Review Narrative", "instructor_action": "Reveal model answer and ask if it is balanced.", "learner_task": "Check if it mentions both improvement and residual risk.", "facilitator_script": "Would this narrative create appropriate urgency without alarm?", "expected_response": "Balanced summary with regional backlog action.", "common_mistakes": "Using overly positive or overly negative tone.", "teaching_takeaway": "Executive narratives should be fair, concise, and action-oriented."}
        ],
        "weak_prompt": "Explain this dashboard.",
        "improved_prompt": "Write a leadership summary of these dashboard metrics.",
        "strong_prompt": "Act as a data storytelling advisor. Convert the following dashboard summary into a concise leadership narrative. Separate improvements, missed targets, operational concerns, and recommended actions. Do not overstate causality; clearly mark what the dashboard does and does not prove.",
        "why_weak": "It may produce a generic explanation and repeat metrics without insight.",
        "why_strong": "It asks for balanced interpretation and explicit caution against causal overclaiming.",
        "expected_output_structure": "Headline; What improved; What remains below target; Operational concern; Recommended action; Caveat.",
        "ideal_output": "The narrative should state that service volume rose, digital adoption crossed target, resolution time and old backlog improved, but closure rate, resolution time, and escalation rate remain outside target. Leadership should focus on the two high-backlog regional teams.",
        "common_mistakes": ["Overstating causality", "Ignoring targets", "Listing metrics without narrative", "Missing regional concentration"],
        "discussion_questions": ["What is the headline?", "Which number deserves leadership attention?", "What cannot be concluded?"],
        "debrief_question": "Why should dashboard narratives avoid unsupported causal claims?",
        "debrief_answer": "Because descriptive metrics show patterns, not necessarily causes. Causal claims need additional evidence.",
        "instructor_notes": "Connect this activity to data visualization and storytelling concepts.",
        "key_takeaway": "Good dashboard narratives combine comparison, context, caveat, and action.",
        "extension_activity": "Ask learners to create a 60-second verbal leadership update."
    },
    "Risk Context to Risk Register": {
        "duration": "20 min",
        "activity_type": "Risk management",
        "mode": "Groups",
        "objective": "Create a structured risk register from an initiative context.",
        "business_context": "A team is implementing AI-assisted reporting. Learners must identify adoption, privacy, accuracy, resistance, and governance risks.",
        "sample_input": "Pilot: no-cost AI-assisted report drafting for three departments over six weeks. Users will prepare first drafts of meeting summaries, briefs, and action trackers using non-sensitive content. Concerns: accidental sensitive data entry, unverified AI output, inconsistent safe-use rules, resistance due to job concerns, variable output quality.",
        "instructions": "1. Show initiative context. 2. Ask learners to identify risks. 3. Build risk-register prompt. 4. Review likelihood, impact, mitigation, and owner.",
        "steps": [
            {"title": "Step 1: Identify Risk Types", "button_label": "Step 1: Identify Risk Types", "instructor_action": "Ask groups to identify at least five risks.", "learner_task": "Classify risks as privacy, accuracy, adoption, governance, or quality.", "facilitator_script": "Which risks could stop the pilot or damage trust?", "expected_response": "Sensitive data exposure, hallucinated outputs, inconsistent rules, resistance, poor prompt quality.", "common_mistakes": "Listing benefits instead of risks.", "teaching_takeaway": "Risk identification starts from failure modes."},
            {"title": "Step 2: Rate Risks", "button_label": "Step 2: Rate Risks", "instructor_action": "Ask groups to assign likelihood and impact.", "learner_task": "Use High/Medium/Low ratings with rationale.", "facilitator_script": "What makes a risk high impact even if likelihood is medium?", "expected_response": "Sensitive data exposure is high impact; output quality may be medium/high likelihood.", "common_mistakes": "Rating everything high.", "teaching_takeaway": "Risk rating needs relative judgment."},
            {"title": "Step 3: Add Controls", "button_label": "Step 3: Add Controls", "instructor_action": "Ask for mitigation and owner.", "learner_task": "Assign preventive and detective controls.", "facilitator_script": "Who owns the mitigation? A risk without an owner is a wish.", "expected_response": "Training lead, department reviewer, programme head, IT support.", "common_mistakes": "Writing vague mitigations like 'be careful'.", "teaching_takeaway": "Controls must be actionable."},
            {"title": "Step 4: Review Register", "button_label": "Step 4: Review Register", "instructor_action": "Reveal model risk register.", "learner_task": "Identify missing controls or owners.", "facilitator_script": "Which control would you implement before launch?", "expected_response": "Safe-use checklist and mandatory human review.", "common_mistakes": "Ignoring review governance.", "teaching_takeaway": "Responsible AI adoption needs governance before scaling."}
        ],
        "weak_prompt": "Make a risk register.",
        "improved_prompt": "Create a risk register for this AI reporting pilot.",
        "strong_prompt": "Act as a risk management advisor. Create a risk register for the following AI-assisted reporting pilot. Include risk description, category, likelihood, impact, mitigation, owner, early warning indicator, and review frequency. Do not invent project facts beyond the supplied context.",
        "why_weak": "It does not specify columns, categories, or factual boundaries.",
        "why_strong": "It creates a complete register and prevents unsupported project assumptions.",
        "expected_output_structure": "Risk table with description, category, likelihood, impact, mitigation, owner, indicator, review frequency.",
        "ideal_output": "The register should include privacy breach, hallucinated output, inconsistent rules, resistance, variable output quality, and weak review discipline, each with practical controls and owners.",
        "common_mistakes": ["No owner", "Generic controls", "No early warning indicator", "Inventing technical systems"],
        "discussion_questions": ["Which risk is highest impact?", "Which control is easiest to implement?", "Who should own review?"],
        "debrief_question": "What risk control is essential before allowing AI-assisted management drafts?",
        "debrief_answer": "A clear safe-use rule and mandatory human verification before circulation are essential.",
        "instructor_notes": "Strong activity for responsible AI governance.",
        "key_takeaway": "AI pilots need operational risk controls, not only enthusiasm.",
        "extension_activity": "Ask groups to add a risk heat map."
    },
    "Stakeholder Concern to Communication Draft": {
        "duration": "18 min",
        "activity_type": "Communication design",
        "mode": "Pairs",
        "objective": "Convert stakeholder concerns into a clear, reassuring implementation communication.",
        "business_context": "A dashboard rollout creates concern that transparency may be used for blame. Learners must draft communication that builds trust and explains support.",
        "sample_input": "A new reporting dashboard will be implemented across departments. Senior leaders want concise performance visibility. Department heads worry about workload and accuracy. Reporting coordinators need templates and training. Some departments fear that dashboard transparency may be used for blame rather than improvement.",
        "instructions": "1. Show stakeholder context. 2. Ask learners to identify concerns by group. 3. Build communication prompt. 4. Review tone and completeness.",
        "steps": [
            {"title": "Step 1: Map Stakeholders", "button_label": "Step 1: Map Stakeholders", "instructor_action": "Ask learners to list stakeholder groups and concerns.", "learner_task": "Map interest, concern, and preferred message.", "facilitator_script": "Who needs reassurance, who needs clarity, and who needs action instructions?", "expected_response": "Leaders need visibility; department heads need workload clarity; coordinators need training; staff need trust.", "common_mistakes": "Writing one generic message for all.", "teaching_takeaway": "Communication improves when stakeholder concerns are explicit."},
            {"title": "Step 2: Select Tone", "button_label": "Step 2: Select Tone", "instructor_action": "Ask what tone is appropriate.", "learner_task": "Choose constructive, transparent, supportive tone.", "facilitator_script": "How do we avoid making this sound like surveillance?", "expected_response": "Emphasise improvement, support, templates, and learning.", "common_mistakes": "Using compliance-heavy language too early.", "teaching_takeaway": "Tone affects adoption."},
            {"title": "Step 3: Build Prompt", "button_label": "Step 3: Build Prompt", "instructor_action": "Guide learners to request communication and FAQ points.", "learner_task": "Ask for message, action required, timeline, and reassurance.", "facilitator_script": "What must the message ask people to do?", "expected_response": "Attend training, submit KPI definitions, use templates, raise concerns.", "common_mistakes": "No clear call to action.", "teaching_takeaway": "Good stakeholder communication includes action and reassurance."},
            {"title": "Step 4: Review Draft", "button_label": "Step 4: Review Draft", "instructor_action": "Reveal model communication and evaluate.", "learner_task": "Check clarity, tone, and stakeholder fit.", "facilitator_script": "Would a sceptical department feel heard?", "expected_response": "Draft should be transparent and non-blaming.", "common_mistakes": "Overpromising that data will never be used for accountability.", "teaching_takeaway": "Trust-building communication must be accurate and respectful."}
        ],
        "weak_prompt": "Write an email about the dashboard rollout.",
        "improved_prompt": "Draft a stakeholder email for a new reporting dashboard rollout.",
        "strong_prompt": "Act as a change communication specialist. Draft a stakeholder communication for the following dashboard rollout. Address senior leaders, department heads, coordinators, and end users. Use a constructive non-blaming tone, explain purpose, support available, action required, timeline, and how concerns will be handled.",
        "why_weak": "It ignores stakeholder differences and adoption concerns.",
        "why_strong": "It maps audience groups, tone, purpose, support, action, timeline, and concern handling.",
        "expected_output_structure": "Subject; Purpose; What changes; Why it matters; Support available; Actions required; Timeline; Reassurance; Contact.",
        "ideal_output": "The communication should position the dashboard as an improvement and learning tool, not a blame mechanism, while clearly stating templates, training, KPI submission deadlines, and support routes.",
        "common_mistakes": ["Generic email", "No reassurance", "No timeline", "No support channel", "Blame-oriented tone"],
        "discussion_questions": ["Who might resist?", "What phrase builds trust?", "What action is required?"],
        "debrief_question": "What makes AI-generated stakeholder communication risky?",
        "debrief_answer": "It may use the wrong tone, omit sensitive concerns, or overpromise unless reviewed by the change owner.",
        "instructor_notes": "Great for communication and change management sessions.",
        "key_takeaway": "Stakeholder prompts should specify audience, concern, tone, and action.",
        "extension_activity": "Ask learners to create a short FAQ for sceptical departments."
    },
    "Performance Observation to Constructive Feedback": {
        "duration": "18 min",
        "activity_type": "People management",
        "mode": "Individual",
        "objective": "Turn performance observations into balanced, constructive feedback.",
        "business_context": "Managers often have raw observations but struggle to write developmental feedback that is specific, fair, and respectful.",
        "sample_input": "The employee sends programme reminders on schedule, communicates respectfully, and created a checklist that reduced missing materials. Development areas: attendance sheets sometimes contain errors, status updates mix confirmed and pending information, scheduling conflicts are flagged late, and closure reports need more analysis.",
        "instructions": "1. Show observations. 2. Ask learners to separate strengths and development areas. 3. Build feedback prompt. 4. Reveal constructive feedback draft.",
        "steps": [
            {"title": "Step 1: Separate Evidence", "button_label": "Step 1: Separate Evidence", "instructor_action": "Ask learners to mark observable facts.", "learner_task": "Separate strengths, development areas, and examples.", "facilitator_script": "Constructive feedback should be based on behaviour, not personality labels.", "expected_response": "Strengths and development areas identified with specific examples.", "common_mistakes": "Using vague labels such as careless or weak.", "teaching_takeaway": "Feedback must be evidence-based."},
            {"title": "Step 2: Balance Tone", "button_label": "Step 2: Balance Tone", "instructor_action": "Ask what tone is fair and professional.", "learner_task": "Suggest wording that is respectful and developmental.", "facilitator_script": "How can we be clear without sounding harsh?", "expected_response": "Acknowledge strengths and specify development priorities.", "common_mistakes": "Either too soft or too critical.", "teaching_takeaway": "Balanced feedback combines appreciation and clarity."},
            {"title": "Step 3: Build Prompt", "button_label": "Step 3: Build Prompt", "instructor_action": "Guide prompt for structured feedback and goals.", "learner_task": "Ask for strengths, development areas, examples, goals, and support.", "facilitator_script": "What output would be useful in a review meeting?", "expected_response": "Feedback paragraph plus development goals.", "common_mistakes": "No future action plan.", "teaching_takeaway": "Feedback should lead to improvement steps."},
            {"title": "Step 4: Review Draft", "button_label": "Step 4: Review Draft", "instructor_action": "Reveal draft and ask what a manager must edit.", "learner_task": "Check fairness, accuracy, and tone.", "facilitator_script": "Would you be comfortable saying this to the employee?", "expected_response": "Manager should verify examples and adapt tone.", "common_mistakes": "Sending AI output as-is.", "teaching_takeaway": "AI can help structure feedback; managers must personalise responsibly."}
        ],
        "weak_prompt": "Write employee feedback.",
        "improved_prompt": "Write balanced feedback from these performance observations.",
        "strong_prompt": "Act as a people manager preparing constructive performance feedback. Use the following observations to write balanced feedback with strengths, development areas, behavioural examples, two improvement goals, and support actions. Avoid personality judgments and do not invent ratings or incidents.",
        "why_weak": "It may create generic praise or criticism without evidence.",
        "why_strong": "It forces behavioural evidence, balance, goals, and factual boundaries.",
        "expected_output_structure": "Opening appreciation; Strengths; Development areas; Examples; Goals; Support; Closing encouragement.",
        "ideal_output": "The feedback should recognise timely reminders and respectful communication, while asking for improved attendance-sheet accuracy, clearer status separation, earlier escalation, and more analytical closure reports.",
        "common_mistakes": ["Personality labels", "Invented ratings", "No examples", "No support plan"],
        "discussion_questions": ["What makes feedback fair?", "Which phrase should be avoided?", "How can goals be measurable?"],
        "debrief_question": "Why should managers review AI-generated feedback carefully?",
        "debrief_answer": "Feedback affects people, trust, and records; it must be accurate, fair, contextual, and respectful.",
        "instructor_notes": "Good opportunity to discuss ethical and interpersonal dimensions of AI.",
        "key_takeaway": "AI-assisted feedback must remain human, evidence-based, and accountable.",
        "extension_activity": "Ask learners to convert feedback into a 30-day development plan."
    },
    "Budget Variance Note to Management Brief": {
        "duration": "18 min",
        "activity_type": "Finance briefing",
        "mode": "Individual",
        "objective": "Convert budget observations into a concise management review note.",
        "business_context": "Q3 spend is higher than Q2 and two budget heads may exceed allocation. Learners must prepare review questions and actions without assuming misconduct.",
        "sample_input": "Q3 spend is 34% higher than Q2. Training programmes, travel, software subscriptions, printing, and consultancy show higher Q3 spend. Some expenses were timing-related, including renewals advanced from Q4 and milestone-based consultancy payment. Two budget heads may exceed annual allocation if Q3 pace continues. Finance needs questions for budget-holder review.",
        "instructions": "1. Show budget note. 2. Ask learners to separate variance, explanation, and risk. 3. Build management brief prompt. 4. Reveal review questions.",
        "steps": [
            {"title": "Step 1: Identify Variance", "button_label": "Step 1: Identify Variance", "instructor_action": "Ask learners what changed and what may be timing-related.", "learner_task": "Separate actual increase from possible timing explanation.", "facilitator_script": "Higher spend is not automatically a problem. What context matters?", "expected_response": "Q3 up 34%, renewals and milestone payments may be timing-related.", "common_mistakes": "Treating variance as misuse.", "teaching_takeaway": "Finance prompts need neutral language."},
            {"title": "Step 2: Identify Review Questions", "button_label": "Step 2: Identify Review Questions", "instructor_action": "Ask what finance should ask budget holders.", "learner_task": "Prepare evidence-seeking questions.", "facilitator_script": "What questions clarify whether variance is structural or timing-related?", "expected_response": "Ask about Q4 commitments, renewals, external faculty sessions, consultancy milestones.", "common_mistakes": "Jumping to cuts without understanding drivers.", "teaching_takeaway": "Good briefs support review, not premature judgment."},
            {"title": "Step 3: Build Prompt", "button_label": "Step 3: Build Prompt", "instructor_action": "Guide a prompt that asks for risks, questions, and next actions.", "learner_task": "Write neutral finance brief prompt.", "facilitator_script": "How do we avoid accusatory framing?", "expected_response": "Use neutral terms like variance drivers, review questions, and monitoring actions.", "common_mistakes": "Using loaded language.", "teaching_takeaway": "Tone matters in financial communication."},
            {"title": "Step 4: Review Brief", "button_label": "Step 4: Review Brief", "instructor_action": "Reveal model brief.", "learner_task": "Check whether it distinguishes timing and overrun risk.", "facilitator_script": "Would this help a finance review meeting?", "expected_response": "Brief gives questions and monitoring actions.", "common_mistakes": "No follow-up timeline.", "teaching_takeaway": "Budget briefs should inform review decisions."}
        ],
        "weak_prompt": "Analyse this budget problem.",
        "improved_prompt": "Prepare a budget review summary from this variance note.",
        "strong_prompt": "Act as a finance review analyst. Convert the following anonymised budget variance note into a concise management brief. Separate confirmed variance, possible timing explanations, overrun risks, questions for budget holders, and immediate monitoring actions. Use neutral language and do not imply misuse without evidence.",
        "why_weak": "It frames the issue as a problem and may produce accusatory language.",
        "why_strong": "It separates evidence from interpretation and requests review questions.",
        "expected_output_structure": "Overview; Variance drivers; Timing explanations; Overrun risks; Review questions; Monitoring actions.",
        "ideal_output": "The brief should note 34% Q3 increase, timing effects, risk of overrun in two heads, and ask budget holders about Q4 commitments, renewal timing, consultancy milestones, and control actions.",
        "common_mistakes": ["Assuming misuse", "Ignoring timing", "No review questions", "No monitoring action"],
        "discussion_questions": ["Which variance needs attention?", "What may be timing-related?", "What should Finance ask?"],
        "debrief_question": "Why should finance prompts use neutral language?",
        "debrief_answer": "Because financial variance does not automatically imply wrongdoing; review should be evidence-based.",
        "instructor_notes": "Good for managerial finance communication.",
        "key_takeaway": "Budget narratives should distinguish evidence, explanation, risk, and review action.",
        "extension_activity": "Ask learners to create a three-question finance review agenda."
    },
    "Procurement Context to Justification Note": {
        "duration": "15 min",
        "activity_type": "Procurement writing",
        "mode": "Individual",
        "objective": "Create a clear procurement justification without inventing budget or vendor details.",
        "business_context": "A training office needs reusable classroom equipment. Learners must justify need, compare options, and mark missing information.",
        "sample_input": "Requirement: 40 reusable tablet stands and 4 wireless presentation clickers for classroom-based digital learning. Purpose: support AI, dashboard, and polling activities during programmes. Options: continue without purchase, borrow devices from departments, or procure a reusable set. Known risks: items may be misplaced, quality varies, compatibility should be checked. Missing information: exact budget head, approved vendor list, warranty, procurement thresholds.",
        "instructions": "1. Show procurement context. 2. Ask learners to identify need and missing information. 3. Build justification prompt. 4. Reveal structured note.",
        "steps": [
            {"title": "Step 1: Clarify Need", "button_label": "Step 1: Clarify Need", "instructor_action": "Ask learners to state the business need.", "learner_task": "Explain why the purchase supports teaching delivery.", "facilitator_script": "What problem does this purchase solve?", "expected_response": "Supports hands-on digital learning and predictable availability.", "common_mistakes": "Listing items without purpose.", "teaching_takeaway": "Procurement notes should justify need, not just describe items."},
            {"title": "Step 2: Compare Options", "button_label": "Step 2: Compare Options", "instructor_action": "Ask learners to compare three options.", "learner_task": "State pros, cons, and risks.", "facilitator_script": "Why is doing nothing also an option?", "expected_response": "Continue, borrow, procure; each has trade-offs.", "common_mistakes": "Ignoring alternatives.", "teaching_takeaway": "A justification is stronger when alternatives are acknowledged."},
            {"title": "Step 3: Mark Missing Information", "button_label": "Step 3: Mark Missing Information", "instructor_action": "Ask what cannot be filled by AI.", "learner_task": "List budget/vendor/threshold information to verify.", "facilitator_script": "What should the AI not invent?", "expected_response": "Budget head, vendor list, warranty, thresholds.", "common_mistakes": "Inventing costs and vendors.", "teaching_takeaway": "AI should flag missing procurement facts."},
            {"title": "Step 4: Review Note", "button_label": "Step 4: Review Note", "instructor_action": "Reveal model note.", "learner_task": "Check whether it is approval-ready or draft-only.", "facilitator_script": "What must be added before official submission?", "expected_response": "Cost, vendor quotes, thresholds, approvals.", "common_mistakes": "Treating draft as final procurement request.", "teaching_takeaway": "Procurement drafts need institutional verification."}
        ],
        "weak_prompt": "Write a procurement justification.",
        "improved_prompt": "Prepare a procurement note for these training items.",
        "strong_prompt": "Act as a procurement documentation assistant. Prepare a justification note from the following non-sensitive procurement context. Include need, purpose, options considered, preferred option, risks, controls, missing information, and approval-ready checklist. Do not invent budget, vendor, warranty, or threshold details.",
        "why_weak": "It may invent cost or vendor information and miss alternatives.",
        "why_strong": "It includes procurement logic and explicit no-invention constraints.",
        "expected_output_structure": "Requirement; Purpose; Options; Preferred option; Risks/controls; Missing information; Approval checklist.",
        "ideal_output": "The note should justify a reusable set, mention predictability and classroom support, compare borrowing/no purchase/procurement, and flag missing budget/vendor/warranty details.",
        "common_mistakes": ["Inventing prices", "No alternatives", "No controls", "No approval checklist"],
        "discussion_questions": ["What makes a procurement note credible?", "What must be verified?", "What control prevents loss?"],
        "debrief_question": "What should AI never invent in procurement documentation?",
        "debrief_answer": "Prices, vendors, approvals, thresholds, warranty terms, and budget heads.",
        "instructor_notes": "Good short exercise for administrative audiences.",
        "key_takeaway": "AI can structure procurement justification, but official facts need verification.",
        "extension_activity": "Ask learners to add a checkout register control."
    },
    "AI Adoption Concern to Change Communication": {
        "duration": "20 min",
        "activity_type": "Change management",
        "mode": "Group discussion",
        "objective": "Draft a communication that addresses staff concerns about AI adoption respectfully.",
        "business_context": "A department is introducing AI-assisted drafting. Staff worry about monitoring, replacement, privacy, and accuracy. The communication must encourage responsible use without dismissing concerns.",
        "sample_input": "The department is introducing AI-assisted drafting for meeting summaries, executive brief drafts, stakeholder emails, training outlines, and risk notes. Purpose: reduce first-draft time and improve structure. AI will not replace human judgement, official approval, policy interpretation, confidential decision-making, or accountability. Concern: some team members worry that AI will increase monitoring or reduce the value of human expertise.",
        "instructions": "1. Show AI adoption context. 2. Ask learners to identify fears and facts. 3. Build communication prompt. 4. Reveal respectful change message.",
        "steps": [
            {"title": "Step 1: Surface Concerns", "button_label": "Step 1: Surface Concerns", "instructor_action": "Ask groups to name likely staff concerns.", "learner_task": "List concerns without judging them.", "facilitator_script": "Resistance often contains useful information. What are people worried about?", "expected_response": "Monitoring, replacement, privacy, accuracy, workload, accountability.", "common_mistakes": "Calling concerns irrational.", "teaching_takeaway": "Respectful change starts by naming concerns."},
            {"title": "Step 2: Clarify Boundaries", "button_label": "Step 2: Clarify Boundaries", "instructor_action": "Ask what AI will and will not do.", "learner_task": "Separate support tasks from human-owned decisions.", "facilitator_script": "Where does human judgement remain essential?", "expected_response": "Approval, judgement, policy interpretation, final communication, accountability.", "common_mistakes": "Overpromising that AI has no impact.", "teaching_takeaway": "Clear boundaries reduce anxiety."},
            {"title": "Step 3: Build Prompt", "button_label": "Step 3: Build Prompt", "instructor_action": "Guide prompt for empathetic communication.", "learner_task": "Ask for message, FAQs, and safe-use rules.", "facilitator_script": "What makes a change message credible?", "expected_response": "Purpose, boundaries, safety rules, support, invitation for questions.", "common_mistakes": "Writing promotional AI hype.", "teaching_takeaway": "Change communication should be balanced, not promotional."},
            {"title": "Step 4: Review Message", "button_label": "Step 4: Review Message", "instructor_action": "Reveal message and ask whether it builds trust.", "learner_task": "Check tone and accuracy.", "facilitator_script": "Would this reduce fear or increase suspicion?", "expected_response": "It should reassure without dismissing risk.", "common_mistakes": "Ignoring privacy rules.", "teaching_takeaway": "Responsible AI adoption is a people-change process."}
        ],
        "weak_prompt": "Tell staff to use AI.",
        "improved_prompt": "Draft an email introducing AI-assisted drafting to the team.",
        "strong_prompt": "Act as a change communication advisor. Draft a respectful internal message introducing AI-assisted drafting. Explain purpose, supported use cases, what AI will not replace, privacy rules, human review requirements, support available, and a short FAQ addressing concerns about monitoring, accuracy, and job replacement.",
        "why_weak": "It sounds directive and ignores legitimate concerns.",
        "why_strong": "It addresses adoption psychology, safeguards, use boundaries, and FAQ needs.",
        "expected_output_structure": "Subject; Opening reassurance; Purpose; What AI supports; What remains human; Safety rules; Support; FAQ; Closing.",
        "ideal_output": "The message should frame AI as drafting support, preserve human expertise, prohibit sensitive data entry, require verification, and invite questions.",
        "common_mistakes": ["AI hype", "Ignoring job concerns", "No privacy rules", "No support path", "Overpromising productivity"],
        "discussion_questions": ["What concern is most valid?", "What should the message not say?", "How do we build trust?"],
        "debrief_question": "Why is AI adoption communication different from ordinary tool training communication?",
        "debrief_answer": "AI adoption affects trust, identity, accountability, privacy, and perceived job security, not only tool usage.",
        "instructor_notes": "Good for senior management and HR audiences.",
        "key_takeaway": "AI change communication must be honest, bounded, and human-centred.",
        "extension_activity": "Ask groups to create three FAQ answers for sceptical staff."
    },
    "Scenario Planning for Management Decision": {
        "duration": "20 min",
        "activity_type": "Scenario planning",
        "mode": "Groups",
        "objective": "Generate optimistic, realistic, and risk-sensitive scenarios for a management initiative.",
        "business_context": "Leadership wants a phased AI-assisted drafting implementation plan but faces uncertainty about staff readiness, policy adoption, and review burden.",
        "sample_input": "A professional training institution plans to introduce AI-assisted drafting tools for internal programme administration. Benefits may include faster briefs, cleaner meeting summaries, and better action tracking. Staff experience with AI varies. Some are enthusiastic; others worry about data privacy, accuracy, and misuse. Leadership wants a three-month phased implementation plan.",
        "instructions": "1. Present ambiguous situation. 2. Ask groups to identify uncertainties. 3. Build scenario prompt. 4. Compare optimistic, realistic, and risk-sensitive scenarios.",
        "steps": [
            {"title": "Step 1: Identify Uncertainties", "button_label": "Step 1: Identify Uncertainties", "instructor_action": "Ask groups what is uncertain.", "learner_task": "List adoption, policy, review, and training uncertainties.", "facilitator_script": "Scenario planning starts with uncertainty, not prediction.", "expected_response": "Policy readiness, staff compliance, review burden, standardisation, training time.", "common_mistakes": "Predicting only one future.", "teaching_takeaway": "Scenarios prepare managers for multiple futures."},
            {"title": "Step 2: Define Three Scenarios", "button_label": "Step 2: Define Three Scenarios", "instructor_action": "Ask for optimistic, realistic, and risk-sensitive versions.", "learner_task": "Describe what changes under each scenario.", "facilitator_script": "What must be true for the optimistic case? What could go wrong?", "expected_response": "Smooth adoption, partial adoption, delayed adoption with privacy concerns.", "common_mistakes": "Making scenarios too similar.", "teaching_takeaway": "Useful scenarios differ meaningfully."},
            {"title": "Step 3: Build Prompt", "button_label": "Step 3: Build Prompt", "instructor_action": "Guide a prompt for scenarios, triggers, and actions.", "learner_task": "Ask for indicators and management responses.", "facilitator_script": "How will leadership know which scenario is emerging?", "expected_response": "Early indicators and response actions for each scenario.", "common_mistakes": "No trigger indicators.", "teaching_takeaway": "Scenarios need monitoring signals."},
            {"title": "Step 4: Compare Plans", "button_label": "Step 4: Compare Plans", "instructor_action": "Ask groups to select most likely scenario.", "learner_task": "Justify with evidence needed.", "facilitator_script": "What evidence would confirm or disconfirm your scenario?", "expected_response": "Training uptake, safe-use compliance, output quality, review workload.", "common_mistakes": "Choosing preferred scenario rather than likely scenario.", "teaching_takeaway": "Scenario planning improves readiness, not certainty."}
        ],
        "weak_prompt": "Make scenarios for this.",
        "improved_prompt": "Create optimistic, realistic, and risky scenarios for AI adoption.",
        "strong_prompt": "Act as a strategic planning facilitator. Develop optimistic, realistic, and risk-sensitive scenarios for the following AI-assisted drafting initiative. For each scenario, include assumptions, early warning indicators, management actions, risks, and evidence that would confirm or disconfirm the scenario. Keep recommendations practical for a three-month horizon.",
        "why_weak": "It does not define scenario types, planning horizon, or decision use.",
        "why_strong": "It links scenarios to assumptions, indicators, actions, and evidence.",
        "expected_output_structure": "Scenario table with assumptions, indicators, risks, management actions, evidence to monitor.",
        "ideal_output": "The scenarios should range from smooth adoption with champions, to partial adoption requiring more training, to risk-sensitive delay due to privacy concerns and review burden.",
        "common_mistakes": ["One prediction only", "No indicators", "No management actions", "Overly dramatic scenarios"],
        "discussion_questions": ["Which scenario is most likely?", "What signal would change your view?", "What action is common across scenarios?"],
        "debrief_question": "How is scenario planning different from prediction?",
        "debrief_answer": "Prediction tries to identify one future; scenario planning prepares for several plausible futures and their signals.",
        "instructor_notes": "Useful as a closing activity for executive audiences.",
        "key_takeaway": "AI strategy should prepare for multiple adoption paths.",
        "extension_activity": "Ask groups to create a 30-60-90 day implementation plan."
    }
}

# Additional concise expansions preserve existing CSV activities that are not in the main 15 list.
ACTIVITY_STUDIO.update({
    "Risk Classification Game": {
        "duration": "10 min", "activity_type": "Group activity", "mode": "Groups",
        "objective": "Practise classifying AI scenarios as allowed, restricted, or prohibited.",
        "business_context": "Managers need quick judgement on which AI uses are safe, which need review, and which should be avoided.",
        "sample_input": "Scenario: Using AI to summarise a public government report.",
        "instructions": "1. Show each scenario. 2. Groups vote allowed/restricted/prohibited. 3. Reveal answer and rationale. 4. Discuss disagreements.",
        "steps": [
            {"title":"Step 1: Show Scenario","button_label":"Step 1: Show Scenario","instructor_action":"Display one scenario at a time.","learner_task":"Vote individually first.","facilitator_script":"Classify this use before discussing.","expected_response":"Public report summary is generally allowed with verification.","common_mistakes":"Ignoring verification just because data is public.","teaching_takeaway":"Low-risk does not mean no review."},
            {"title":"Step 2: Discuss Classification","button_label":"Step 2: Discuss Classification","instructor_action":"Ask groups to justify classification.","learner_task":"Explain why the use is allowed/restricted/prohibited.","facilitator_script":"Which rule guided your classification?","expected_response":"Data sensitivity and decision impact drive risk level.","common_mistakes":"Classifying based on tool brand rather than use case.","teaching_takeaway":"Risk follows use context."},
            {"title":"Step 3: Reveal Rationale","button_label":"Step 3: Reveal Rationale","instructor_action":"Reveal the answer and reasoning.","learner_task":"Compare with group reasoning.","facilitator_script":"What did your group miss?","expected_response":"Need fact-checking even for public summaries.","common_mistakes":"Forgetting hallucination risk.","teaching_takeaway":"Verification remains mandatory."},
            {"title":"Step 4: Transfer Rule","button_label":"Step 4: Transfer Rule","instructor_action":"Ask learners to create a general rule.","learner_task":"Write one safe-use rule.","facilitator_script":"How would you explain this rule to a colleague?","expected_response":"Use public/non-sensitive data and verify outputs before use.","common_mistakes":"Creating too broad a rule.","teaching_takeaway":"Rules should be memorable and practical."}
        ],
        "weak_prompt":"Is this okay?", "improved_prompt":"Classify this AI use case as low, medium, or high risk.",
        "strong_prompt":"Act as a responsible AI reviewer. Classify the following AI use case as allowed, restricted, or prohibited. Explain the data-sensitivity issue, decision-impact risk, required human review, and any safer alternative.",
        "why_weak":"It gives no classification criteria.", "why_strong":"It asks for criteria, rationale, review need, and safer alternative.",
        "expected_output_structure":"Classification; Rationale; Review needed; Safer alternative.", "ideal_output":"Allowed/low-risk if the report is public, but summary must still be fact-checked.",
        "common_mistakes":["No verification", "Ignoring data sensitivity", "Overgeneralising"], "discussion_questions":["What makes this low-risk?", "What still needs review?"],
        "debrief_question":"Were there any scenarios where your group disagreed?", "debrief_answer":"Disagreement usually arises when data sensitivity or decision impact is ambiguous.",
        "instructor_notes":"Use quick voting to keep energy high.", "key_takeaway":"Responsible AI classification depends on data, context, and impact.", "extension_activity":"Ask groups to create two new scenarios."
    },
    "Prompt Building Competition": {
        "duration":"20 min", "activity_type":"Competitive", "mode":"Groups", "objective":"Build the strongest possible prompt for an executive task.",
        "business_context":"Groups compete to design prompts that are complete, safe, and decision-ready.", "sample_input":"Prepare a risk register for a new training programme initiative.",
        "instructions":"1. Assign same task. 2. Groups build prompts. 3. Read prompts aloud. 4. Vote on strongest prompt.",
        "steps":[
            {"title":"Step 1: Assign Task","button_label":"Step 1: Assign Task","instructor_action":"Give all groups the same executive task.","learner_task":"Clarify expected output.","facilitator_script":"Your goal is not the longest prompt; it is the most controlled prompt.","expected_response":"Groups identify risk register as output.","common_mistakes":"No role or format.","teaching_takeaway":"Competition highlights prompt design trade-offs."},
            {"title":"Step 2: Build Prompt","button_label":"Step 2: Build Prompt","instructor_action":"Give groups 5 minutes.","learner_task":"Use R-C-T-O-F-E.","facilitator_script":"Check whether your prompt has role, context, task, output, format, and evaluation.","expected_response":"Structured prompt with risk columns.","common_mistakes":"Generic prompt.","teaching_takeaway":"Frameworks improve completeness."},
            {"title":"Step 3: Peer Review","button_label":"Step 3: Peer Review","instructor_action":"Ask groups to score another prompt.","learner_task":"Identify missing elements.","facilitator_script":"Score for usefulness, safety, and clarity.","expected_response":"Groups identify gaps.","common_mistakes":"Voting based on style only.","teaching_takeaway":"Review criteria matter."},
            {"title":"Step 4: Declare Winner","button_label":"Step 4: Declare Winner","instructor_action":"Select strongest prompt and explain why.","learner_task":"Capture one improvement.","facilitator_script":"What will you add to your next prompt?","expected_response":"Role, format, risk owner, no-invention constraint.","common_mistakes":"No learning reflection.","teaching_takeaway":"Prompting improves through comparison."}
        ],
        "weak_prompt":"Make a risk register for training.", "improved_prompt":"Create a risk register for a new training programme.",
        "strong_prompt":"Act as a risk management advisor. Create a risk register for a new management training programme. Include risk description, likelihood, impact, mitigation, owner, review frequency, and assumptions. Do not invent details not supplied by the user.",
        "why_weak":"It lacks structure and controls.", "why_strong":"It defines role, columns, assumptions, and factual boundary.",
        "expected_output_structure":"Risk table with ownership and review cadence.", "ideal_output":"A strong prompt includes all risk-register fields and no-invention rule.",
        "common_mistakes":["No owner", "No review frequency", "No constraint"], "discussion_questions":["Which prompt was strongest?", "What was missing most often?"],
        "debrief_question":"What was the most common missing element?", "debrief_answer":"Usually format, owner, or evaluation constraint.",
        "instructor_notes":"Award points for each R-C-T-O-F-E element.", "key_takeaway":"Prompt quality can be evaluated systematically.", "extension_activity":"Ask groups to improve the winning prompt further."
    },
    "AI Output Review": {
        "duration":"15 min", "activity_type":"Critical review", "mode":"Individual", "objective":"Critically evaluate an AI-generated document before approval.",
        "business_context":"AI-generated summaries can sound confident but contain unsupported claims. Learners practise review discipline.",
        "sample_input":"AI-generated summary: The training programme achieved a 95% satisfaction rate across all participant groups based on comprehensive feedback analysis.",
        "instructions":"1. Share AI-generated summary. 2. Learners mark what needs verification. 3. Discuss as group. 4. Build review checklist.",
        "steps":[
            {"title":"Step 1: Read Output","button_label":"Step 1: Read Output","instructor_action":"Show AI output only.","learner_task":"Mark claims.","facilitator_script":"Which words sound confident but need evidence?","expected_response":"95%, all participant groups, comprehensive analysis.","common_mistakes":"Trusting fluent language.","teaching_takeaway":"Fluency is not evidence."},
            {"title":"Step 2: Verify Claims","button_label":"Step 2: Verify Claims","instructor_action":"Ask what source evidence is needed.","learner_task":"List verification items.","facilitator_script":"What document would prove this?","expected_response":"Feedback dataset, sample size, group categories.","common_mistakes":"Only checking grammar.","teaching_takeaway":"Review requires evidence tracing."},
            {"title":"Step 3: Build Checklist","button_label":"Step 3: Build Checklist","instructor_action":"Create checklist with learners.","learner_task":"Add fact, tone, completeness, sensitivity checks.","facilitator_script":"What should be checked before circulation?","expected_response":"Fact-check, sensitive data, unsupported claims, tone.","common_mistakes":"No accountability step.","teaching_takeaway":"Checklists make review repeatable."},
            {"title":"Step 4: Improve Output","button_label":"Step 4: Improve Output","instructor_action":"Ask for safer rewrite.","learner_task":"Rewrite with caveats.","facilitator_script":"How can we state this safely?","expected_response":"'The draft claims 95%; verify before use.'","common_mistakes":"Deleting all useful content.","teaching_takeaway":"Safe rewriting preserves usefulness with caveats."}
        ],
        "weak_prompt":"Review this.", "improved_prompt":"Check this AI summary for problems.",
        "strong_prompt":"Act as a human reviewer of AI-assisted management writing. Review the following AI-generated summary for unsupported claims, missing evidence, overconfident wording, sensitive information, and required verification steps. Provide a safer revised version.",
        "why_weak":"It gives no review criteria.", "why_strong":"It specifies concrete review dimensions and asks for safer revision.",
        "expected_output_structure":"Claims needing verification; Risks; Safer rewrite; Review checklist.", "ideal_output":"Flag 95%, all participant groups, and comprehensive feedback analysis as unsupported until source data is verified.",
        "common_mistakes":["Checking style only", "Missing unsupported numbers", "No safer rewrite"], "discussion_questions":["Which claim is riskiest?", "What evidence is needed?"],
        "debrief_question":"How would you build a standard review checklist?", "debrief_answer":"Include source verification, no sensitive data, factual accuracy, tone, assumptions, and accountable reviewer.",
        "instructor_notes":"Excellent for responsible AI verification habit.", "key_takeaway":"AI output must be reviewed against evidence, not fluency.", "extension_activity":"Ask learners to design a five-point checklist."
    },
    "Capstone Group Design": {
        "duration":"30 min", "activity_type":"Capstone", "mode":"Groups", "objective":"Design a complete AI-enabled workflow for a management use case.",
        "business_context":"Teams must translate learning into a realistic AI workflow with human review, risks, and pilot design.",
        "sample_input":"Workflow: Weekly programme reporting currently takes 3 hours per coordinator and produces inconsistent formats.",
        "instructions":"1. Select workflow. 2. Map current process, pain points, AI steps, human review, risks, and pilot plan. 3. Present two-minute summary. 4. Debrief realism and risk.",
        "steps":[
            {"title":"Step 1: Map Current Workflow","button_label":"Step 1: Map Current Workflow","instructor_action":"Ask groups to draw current workflow.","learner_task":"Identify steps and pain points.","facilitator_script":"Where does time get wasted?","expected_response":"Manual data collection and formatting.","common_mistakes":"Jumping to AI before mapping process.","teaching_takeaway":"AI should solve a known workflow pain."},
            {"title":"Step 2: Add AI Role","button_label":"Step 2: Add AI Role","instructor_action":"Ask where AI can help safely.","learner_task":"Define AI-supported steps.","facilitator_script":"Which steps are drafting, summarising, or formatting?","expected_response":"Template standardisation and first-draft narrative.","common_mistakes":"Automating approval.","teaching_takeaway":"AI should support, not replace accountability."},
            {"title":"Step 3: Add Human Review","button_label":"Step 3: Add Human Review","instructor_action":"Ask where human review is mandatory.","learner_task":"Define reviewer and checklist.","facilitator_script":"Who signs off the final report?","expected_response":"Coordinator verifies facts and context.","common_mistakes":"No review checkpoint.","teaching_takeaway":"Human-in-the-loop is non-negotiable."},
            {"title":"Step 4: Present Pilot Plan","button_label":"Step 4: Present Pilot Plan","instructor_action":"Groups present 2-minute plan.","learner_task":"State pilot scope, metrics, and risks.","facilitator_script":"What would make this pilot credible?","expected_response":"Four-week test, one report type, quality/time metrics.","common_mistakes":"No success measure.","teaching_takeaway":"Pilot plans need metrics and risk controls."}
        ],
        "weak_prompt":"Make AI workflow.", "improved_prompt":"Design an AI workflow for weekly programme reporting.",
        "strong_prompt":"Act as an AI workflow design consultant. Design a practical AI-enabled workflow for weekly programme reporting. Include current pain points, AI-supported steps, human review checkpoints, risks, controls, pilot scope, success metrics, and a 4-week rollout plan. Use only no-cost tools and non-sensitive data.",
        "why_weak":"It is too vague for workflow design.", "why_strong":"It covers process, governance, pilot, and safety constraints.",
        "expected_output_structure":"Current workflow; Pain points; AI steps; Human review; Risks; Pilot plan; Metrics.", "ideal_output":"A credible plan uses AI for standard drafts and templates, retains human fact-checking, and pilots with one report type for four weeks.",
        "common_mistakes":["No current process", "No metrics", "No review", "Too much automation"], "discussion_questions":["What remains human?", "What metric proves value?"],
        "debrief_question":"Which element required most discussion?", "debrief_answer":"Usually human review boundaries or success metrics.",
        "instructor_notes":"Use as closing group assignment.", "key_takeaway":"AI workflow design needs process clarity, governance, and measurable pilots.", "extension_activity":"Ask groups to create a one-slide pitch."
    }
})
