"""
Classroom-safe sample inputs for GenAI Executive Management Studio.

Generated from the attached document: "Paste-Ready Placeholder Inputs for
GenAI Executive Management Studio". The examples are synthetic and designed
for classroom demonstration.
"""

INLINE_USE_CASE_SAMPLES = {'Skill-Gap Analysis Brief': [{'title': 'Attached classroom-safe sample',
                               'text': 'Department: Customer Operations\n'
                                       'Period reviewed: Q3 FY2025-26\n'
                                       'Total staff reviewed: 86\n'
                                       'Roles covered: customer desk executives, shift supervisors, '
                                       'complaint-resolution coordinators, reporting assistants\n'
                                       '\n'
                                       'Competency assessment scale: 1 = beginner, 5 = advanced\n'
                                       '1. Data interpretation: Average score 2.6; target score 4.0; 41% of staff '
                                       'below level 3.\n'
                                       '2. Dashboard reading: Average score 2.4; target score 3.8; most staff can read '
                                       'charts but struggle to explain trends.\n'
                                       '3. AI-assisted drafting: Average score 1.9; target score 3.5; limited exposure '
                                       'to prompt writing and verification.\n'
                                       '4. Customer escalation handling: Average score 3.1; target score 4.2; '
                                       'supervisors report inconsistent documentation quality.\n'
                                       '5. Process compliance: Average score 3.5; target score 4.0; strong awareness '
                                       'but weak checklist discipline during peak hours.\n'
                                       '6. Written communication: Average score 2.8; target score 4.0; recurring '
                                       'issues include vague action notes and incomplete closure summaries.\n'
                                       '7. Basic Excel analysis: Average score 2.7; target score 3.8; pivot tables and '
                                       'conditional formatting are not used consistently.\n'
                                       '\n'
                                       'Additional observations:\n'
                                       '- New hires are confident in routine transactions but require support in '
                                       'exception handling.\n'
                                       '- Supervisors spend nearly 25% of their time rewriting status summaries.\n'
                                       '- Two departments requested short practical training rather than lecture-heavy '
                                       'sessions.\n'
                                       '- Leadership wants visible improvement in dashboard interpretation, escalation '
                                       'documentation, and AI-safe reporting within 60 days.'}],
 'Training Module Outline': [{'title': 'Attached classroom-safe sample',
                              'text': 'Topic: Responsible Generative AI and Prompt Engineering for Management Decision '
                                      'Support\n'
                                      'Audience: Mid-to-senior managers from operations, HR, finance, procurement, '
                                      'training, and administration who have basic digital literacy but limited '
                                      'hands-on experience with AI tools.\n'
                                      '\n'
                                      'Context for the training design:\n'
                                      '- Duration: One full day, 6 instructional hours plus breaks.\n'
                                      '- Participants: 35 working professionals.\n'
                                      '- Session objective: Help managers use free AI tools safely for drafting, '
                                      'summarisation, analysis, risk review, and communication.\n'
                                      '- Preferred teaching style: Demonstration-led, interactive, example-rich, and '
                                      'non-technical.\n'
                                      '- Tools allowed: Free web-based AI tools and offline worksheets only.\n'
                                      '- Safety rule: No confidential, personal, financial, or sensitive '
                                      'organisational data should be used.\n'
                                      '- Expected output from the module: Managers should leave with at least three '
                                      'reusable prompts, one AI use-case map, and one personal responsible-use '
                                      'checklist.'}],
 'Process Improvement Note': [{'title': 'Attached classroom-safe sample',
                               'text': 'Current process: Training nomination approval for internal management '
                                       'development programmes.\n'
                                       '\n'
                                       'Step 1: Programme office circulates a nomination email to departments.\n'
                                       'Step 2: Department coordinators collect nominations manually through email '
                                       'replies.\n'
                                       'Step 3: HODs approve nominations by forwarding the same email thread with '
                                       'comments.\n'
                                       'Step 4: Programme office consolidates names in Excel.\n'
                                       'Step 5: Finance confirms budget availability after receiving the consolidated '
                                       'list.\n'
                                       'Step 6: Final participant list is shared with departments two days before the '
                                       'programme.\n'
                                       '\n'
                                       'Observed inefficiencies:\n'
                                       '- Average approval time is 8 working days against the expected 4 days.\n'
                                       '- Duplicate names appear when departments revise lists through separate email '
                                       'threads.\n'
                                       '- Finance often receives incomplete information about employee grade and cost '
                                       'centre.\n'
                                       '- Programme office sends an average of 3 reminder emails per department.\n'
                                       '- Participants sometimes receive confirmation after travel planning '
                                       'deadlines.\n'
                                       '- No single dashboard exists to track approval status by department.\n'
                                       '\n'
                                       'Constraints:\n'
                                       '- The solution should not require paid software.\n'
                                       '- Departments prefer minimal additional data entry.\n'
                                       '- Final approval authority must remain with HODs and Finance.'}],
 'Quarterly Performance Brief': [{'title': 'Attached classroom-safe sample',
                                  'text': 'Quarter: Q3 FY2025-26\n'
                                          'Department: Service Operations\n'
                                          'Reporting period: October-December 2025\n'
                                          '\n'
                                          'KPI Summary:\n'
                                          '1. Service request closure rate: Target 94%; Achieved 91%; Previous quarter '
                                          '89%.\n'
                                          '2. Average resolution time: Target 36 hours; Achieved 42 hours; Previous '
                                          'quarter 47 hours.\n'
                                          '3. Escalation rate: Target below 8%; Achieved 11%; Previous quarter 13%.\n'
                                          '4. Customer satisfaction score: Target 4.2/5; Achieved 4.0/5; Previous '
                                          'quarter 3.8/5.\n'
                                          '5. Digital ticket adoption: Target 80%; Achieved 76%; Previous quarter '
                                          '68%.\n'
                                          '6. Training completion for new workflow: Target 90%; Achieved 82%; Previous '
                                          'quarter not applicable.\n'
                                          '7. Budget utilisation: Target 90%; Achieved 87%; Previous quarter 83%.\n'
                                          '\n'
                                          'Positive developments:\n'
                                          '- Resolution time improved by 5 hours compared with Q2.\n'
                                          '- Digital ticket adoption improved by 8 percentage points.\n'
                                          '- Customer satisfaction improved despite higher request volume.\n'
                                          '\n'
                                          'Concerns:\n'
                                          '- Closure rate remains below target.\n'
                                          '- Escalation rate is still above acceptable threshold.\n'
                                          '- Training completion is uneven across regional teams.\n'
                                          '\n'
                                          'Management note:\n'
                                          'The department expects a 12% increase in service volume in Q4 due to annual '
                                          'closing activities.'}],
 'Status Update Draft': [{'title': 'Attached classroom-safe sample',
                          'text': 'Project: AI-assisted internal reporting pilot\n'
                                  'Reporting date: 15 February 2026\n'
                                  'Project phase: Pilot implementation\n'
                                  'Sponsor: Director-level office\n'
                                  '\n'
                                  'Progress completed:\n'
                                  '- Three departments have submitted sample report templates.\n'
                                  '- A prompt library has been drafted for meeting summaries, executive briefs, risk '
                                  'notes, and dashboard narratives.\n'
                                  '- Two pilot workshops were completed with 42 participants in total.\n'
                                  '- Initial feedback indicates strong interest in templates that reduce drafting '
                                  'time.\n'
                                  '- A responsible-use checklist has been prepared for review.\n'
                                  '\n'
                                  'Current concerns:\n'
                                  '- Some users are still trying to paste sensitive internal details into free AI '
                                  'tools.\n'
                                  '- Departmental reporting formats vary widely, making standardisation difficult.\n'
                                  '- Reviewers requested clearer instructions on human verification before '
                                  'circulation.\n'
                                  '\n'
                                  'Next steps:\n'
                                  '- Finalise the safe-use checklist by 22 February 2026.\n'
                                  '- Conduct one practical clinic for report writers by 28 February 2026.\n'
                                  '- Collect revised templates from departments by 5 March 2026.\n'
                                  '- Prepare leadership review note by 10 March 2026.\n'
                                  '\n'
                                  'Support required:\n'
                                  '- Approval to use a standard disclaimer on all AI-assisted draft outputs.\n'
                                  '- Nomination of one reviewer from each department.'}],
 'Patient Flow Summary': [{'title': 'Attached classroom-safe sample',
                           'text': 'Facility: Outpatient services block\n'
                                   'Period reviewed: 1-15 January 2026\n'
                                   'Data is synthetic and anonymised for training.\n'
                                   '\n'
                                   'Daily average patient count: 420\n'
                                   'Registration counters: 4\n'
                                   'Consultation rooms: 12\n'
                                   'Pharmacy counters: 3\n'
                                   'Diagnostic sample collection counters: 2\n'
                                   '\n'
                                   'Average waiting time by stage:\n'
                                   '- Registration: 22 minutes; target 15 minutes\n'
                                   '- Initial nursing assessment: 18 minutes; target 15 minutes\n'
                                   '- Doctor consultation: 48 minutes; target 35 minutes\n'
                                   '- Billing after consultation: 14 minutes; target 10 minutes\n'
                                   '- Pharmacy dispensing: 37 minutes; target 20 minutes\n'
                                   '- Diagnostic sample collection: 31 minutes; target 25 minutes\n'
                                   '\n'
                                   'Peak congestion windows:\n'
                                   '- 9:30 AM-11:30 AM at registration and consultation.\n'
                                   '- 12:30 PM-2:00 PM at pharmacy.\n'
                                   '\n'
                                   'Operational observations:\n'
                                   '- Two pharmacy counters remain underused before 11:30 AM but are overloaded after '
                                   '12:30 PM.\n'
                                   '- Follow-up patients and new patients currently use the same registration queue.\n'
                                   '- Doctors report incomplete pre-consultation forms in nearly 18% of cases.\n'
                                   '- Patients frequently return to billing due to unclear payment category '
                                   'selection.\n'
                                   '\n'
                                   'Constraint:\n'
                                   'Recommendations should focus on administrative flow, not clinical '
                                   'decision-making.'}],
 'Policy Simplification Brief': [{'title': 'Attached classroom-safe sample',
                                  'text': 'Public Policy Extract: Internal Digital Tool Usage and Data Handling '
                                          'Guidelines\n'
                                          '\n'
                                          'Clause 1: Employees may use approved digital tools to support drafting, '
                                          'summarisation, scheduling, training preparation, and non-sensitive '
                                          'analysis.\n'
                                          '\n'
                                          'Clause 2: Confidential, personally identifiable, financial, legal, '
                                          'disciplinary, medical, procurement-sensitive, or unpublished strategic '
                                          'information must not be entered into public AI or third-party tools unless '
                                          'formal approval has been granted by the authorised data protection office.\n'
                                          '\n'
                                          'Clause 3: Any AI-assisted output used for official communication must be '
                                          'reviewed by the responsible officer before circulation. The officer remains '
                                          'accountable for factual accuracy, tone, completeness, and compliance.\n'
                                          '\n'
                                          'Clause 4: AI-generated summaries of policies, contracts, or compliance '
                                          'documents must be treated as working drafts only and must not replace '
                                          'official interpretation by authorised personnel.\n'
                                          '\n'
                                          'Clause 5: Departments using AI-assisted tools for recurring workflows '
                                          'should maintain a record of approved use cases, review steps, and '
                                          'escalation points.\n'
                                          '\n'
                                          'Clause 6: Staff should clearly mark AI-assisted drafts when submitting them '
                                          'for internal review, unless an approved institutional workflow states '
                                          'otherwise.'}],
 'Appraisal Feedback Draft': [{'title': 'Attached classroom-safe sample',
                               'text': 'Role: Department coordination executive\n'
                                       'Review period: April-December 2025\n'
                                       'Note: This is synthetic and anonymised. Do not use real names.\n'
                                       '\n'
                                       'Observed strengths:\n'
                                       '- Consistently submits weekly coordination updates on time.\n'
                                       '- Maintains a polite and professional tone in most internal communications.\n'
                                       '- Helped standardise the meeting agenda template used by the department.\n'
                                       '- Responds quickly to routine information requests from team members.\n'
                                       '- Demonstrated improvement in spreadsheet formatting after attending a short '
                                       'workshop.\n'
                                       '\n'
                                       'Observed development areas:\n'
                                       '- Sometimes shares status updates without clearly separating completed work, '
                                       'pending work, and risks.\n'
                                       '- Needs closer attention to version control when multiple document drafts are '
                                       'circulated.\n'
                                       '- Escalates delays only after repeated follow-up instead of flagging early '
                                       'warning signs.\n'
                                       '- Could improve confidence in presenting updates during review meetings.\n'
                                       '\n'
                                       'Specific examples:\n'
                                       '- The October review tracker was submitted ahead of deadline but contained two '
                                       'duplicate entries.\n'
                                       '- The November workshop report was well formatted but did not include '
                                       'participant feedback themes.\n'
                                       '- During the December planning meeting, the executive provided useful '
                                       'logistical inputs but did not summarise open decisions.\n'
                                       '\n'
                                       'Development suggestion:\n'
                                       'Focus on structured reporting, proactive escalation, and concise verbal '
                                       'updates.'}],
 'Lessons Learned Summary': [{'title': 'Attached classroom-safe sample',
                              'text': 'Project: Department-wide dashboard adoption pilot\n'
                                      'Duration: August-November 2025\n'
                                      'Objective: Introduce a standard dashboard format for monthly service '
                                      'reporting.\n'
                                      '\n'
                                      'Project notes:\n'
                                      '- The pilot began with five departments but only three submitted complete '
                                      'baseline data on time.\n'
                                      '- Initial dashboard templates were too detailed for senior leadership review.\n'
                                      '- A simplified one-page dashboard was introduced in month two and received '
                                      'better acceptance.\n'
                                      '- Teams requested examples showing how to convert dashboard findings into '
                                      'management actions.\n'
                                      '- The data team underestimated the time required to clean inconsistent '
                                      'department-level formats.\n'
                                      '- Weekly office-hour clinics helped users resolve small issues quickly.\n'
                                      '- Department coordinators appreciated short video explainers more than long '
                                      'written manuals.\n'
                                      '- Senior leaders asked for clearer colour coding and exception flags.\n'
                                      '- The pilot reduced manual report compilation time for participating '
                                      'departments by an estimated 20%.\n'
                                      '- Future rollout should begin with a common data dictionary and a two-week '
                                      'preparation window.\n'
                                      '\n'
                                      'Open concern:\n'
                                      'Some departments still rely on manual Excel files that are not updated '
                                      'consistently.'}],
 'Meeting Summary with Action Items': [{'title': 'Attached classroom-safe sample',
                                        'text': 'Meeting: Monthly operations review\n'
                                                'Date: 12 March 2026\n'
                                                'Time: 3:00 PM-4:15 PM\n'
                                                'Participants: Operations Head, Finance Officer, Training Coordinator, '
                                                'IT Support Lead, Department Coordinators\n'
                                                '\n'
                                                'Agenda:\n'
                                                '1. Review of February service performance\n'
                                                '2. Pending training nominations\n'
                                                '3. Digital ticketing adoption\n'
                                                '4. Budget utilisation for Q4\n'
                                                '\n'
                                                'Discussion notes:\n'
                                                '- February service request volume increased by 9% compared with '
                                                'January.\n'
                                                '- Closure rate improved from 88% to 91%, but remains below the 94% '
                                                'target.\n'
                                                '- IT Support Lead reported that 18% of tickets are still being '
                                                'submitted by email instead of the portal.\n'
                                                '- Training Coordinator stated that two departments have not sent '
                                                'final nominations for the dashboard workshop.\n'
                                                '- Finance Officer confirmed that Q4 training budget is available, but '
                                                'all invoices must be submitted by 25 March.\n'
                                                '- Operations Head asked coordinators to reduce duplicate escalation '
                                                'emails.\n'
                                                '\n'
                                                'Decisions:\n'
                                                '- Continue the digital ticketing awareness campaign for one more '
                                                'month.\n'
                                                '- Conduct a 90-minute dashboard workshop in the last week of March.\n'
                                                '- Use a single tracker for pending escalations from 18 March onward.\n'
                                                '\n'
                                                'Action points:\n'
                                                '- IT Support Lead to share department-wise portal usage report by 15 '
                                                'March.\n'
                                                '- Training Coordinator to circulate final workshop schedule by 16 '
                                                'March.\n'
                                                '- Department Coordinators to submit pending nominations by 17 March.\n'
                                                '- Finance Officer to send invoice submission checklist by 14 March.\n'
                                                '\n'
                                                'Open issue:\n'
                                                'No decision was taken on whether email-based tickets will be formally '
                                                'restricted from April.'}],
 'Delay Root-Cause Brief': [{'title': 'Attached classroom-safe sample',
                             'text': 'Delay Report: Regional equipment delivery for service centre upgrade\n'
                                     'Report date: 20 April 2026\n'
                                     'Original delivery commitment: 15 April 2026\n'
                                     'Revised expected delivery: 24 April 2026\n'
                                     'Shipment contents: 24 desktop systems, 12 barcode scanners, 3 network switches, '
                                     'and installation accessories\n'
                                     'Affected locations: North Zone service centres A, B, and C\n'
                                     '\n'
                                     'Timeline:\n'
                                     '- 5 April: Purchase order released to vendor.\n'
                                     '- 8 April: Vendor confirmed dispatch readiness.\n'
                                     '- 10 April: Shipment picked up from warehouse.\n'
                                     '- 12 April: Transporter reported route diversion due to highway maintenance.\n'
                                     '- 14 April: Partial shipment reached regional hub; 8 desktop systems and 4 '
                                     'scanners were missing from the manifest.\n'
                                     '- 15 April: Local installation team arrived as originally scheduled but could '
                                     'not proceed fully.\n'
                                     '- 16 April: Vendor confirmed that missing items were held back due to packaging '
                                     'mismatch.\n'
                                     '- 18 April: Replacement dispatch initiated.\n'
                                     '\n'
                                     'Operational impact:\n'
                                     '- Installation at Centre A is 60% complete.\n'
                                     '- Centres B and C have not started installation.\n'
                                     '- Training for front-desk staff scheduled for 22 April may need rescheduling.\n'
                                     '- Old systems are still functional but slow during peak service hours.\n'
                                     '\n'
                                     'Possible contributing factors:\n'
                                     '- Dispatch checklist was not cross-verified against the purchase order.\n'
                                     '- Transporter route change was not communicated to the installation team.\n'
                                     '- Vendor and local project team used separate tracking sheets.\n'
                                     '- No contingency buffer was included before the staff training date.\n'
                                     '\n'
                                     'Constraint:\n'
                                     'Recommend short-term actions only; do not suggest changing the vendor contract '
                                     'at this stage.'}],
 'Feedback Theme Clustering': [{'title': 'Attached classroom-safe sample',
                                'text': '1. The session was practical and helped me understand how to write better '
                                        'prompts for routine reports.\n'
                                        '2. I liked the examples, but I wanted more time to practice on my own '
                                        'departmental cases.\n'
                                        '3. The responsible AI section was useful because it clarified what data '
                                        'should not be pasted into public tools.\n'
                                        '4. The pace was slightly fast during the hands-on activity.\n'
                                        '5. The facilitator explained concepts in simple language without making the '
                                        'topic too technical.\n'
                                        '6. I would like a separate session on using AI for dashboard narratives.\n'
                                        '7. The caselets were relevant, especially the HR and operations examples.\n'
                                        '8. Some prompts were too long; a one-page prompt cheat sheet would help.\n'
                                        '9. The quiz was engaging and made the session more interactive.\n'
                                        '10. The training should include a short comparison of free AI tools.\n'
                                        '11. I am still unsure how to verify AI-generated output before sending it '
                                        'officially.\n'
                                        '12. The examples were useful, but finance-specific cases were limited.\n'
                                        '13. The session helped reduce fear of using AI, but I need more guided '
                                        'practice.\n'
                                        '14. The discussion on hallucination risk was very important for managers.\n'
                                        '15. I liked that the session did not require coding.\n'
                                        '16. More time should be given for group discussion.\n'
                                        '17. The prompt builder framework was easy to remember.\n'
                                        '18. I would like downloadable templates for meeting summaries and risk '
                                        'registers.\n'
                                        '19. The session was relevant for my work, especially report drafting.\n'
                                        '20. The closing reflection helped me identify one AI use case for my '
                                        'department.'}]}

CSV_USE_CASE_SAMPLES = {'Workforce Planning Brief': [{'title': 'Attached classroom-safe sample',
                               'text': 'Workforce observations for leadership brief:\n'
                                       '- Department strength: 124 employees across operations, customer support, '
                                       'reporting, and field coordination.\n'
                                       '- Attrition in the last six months: 11.5%, concentrated among employees with '
                                       '1-3 years of experience.\n'
                                       '- Critical vacancies: 6 supervisor roles, 3 reporting analyst roles, and 8 '
                                       'front-line service roles.\n'
                                       '- Skill-gap pattern: Strong process knowledge but weak data interpretation, '
                                       'dashboard explanation, and AI-assisted drafting.\n'
                                       '- Training participation: 62% completed the last digital reporting workshop; '
                                       'target was 85%.\n'
                                       '- Internal mobility: 14 employees expressed interest in analytics-oriented '
                                       'roles but only 5 meet current competency requirements.\n'
                                       '- Workload issue: Supervisors report increased time spent correcting '
                                       'documentation and preparing leadership summaries.\n'
                                       '- Risk: If reporting skills do not improve before Q1, turnaround time for '
                                       'monthly reviews may increase.\n'
                                       '- Immediate opportunity: Create a 30-day micro-training intervention on '
                                       'dashboard reading, escalation notes, and AI-safe summarisation.'}],
 'Training Needs Analysis': [{'title': 'Attached classroom-safe sample',
                              'text': 'Performance observations for training needs analysis:\n'
                                      '- Several managers submit descriptive reports but do not clearly identify '
                                      'implications, risks, or actions.\n'
                                      '- Team members can operate standard dashboards but struggle to explain what '
                                      'changed and why it matters.\n'
                                      '- Meeting minutes often record discussion points but miss decisions, owners, '
                                      'and deadlines.\n'
                                      '- New supervisors are hesitant to give structured feedback and tend to use '
                                      'generic language.\n'
                                      '- Staff are experimenting with free AI tools but do not consistently apply '
                                      'data-safety checks.\n'
                                      '- Some employees can create Excel summaries but are uncomfortable with pivot '
                                      'tables and trend interpretation.\n'
                                      '- Communication quality is uneven: emails are polite but often too long and '
                                      'action requirements are unclear.\n'
                                      '- Teams prefer short demonstrations, templates, and guided practice rather than '
                                      'theory-heavy training.\n'
                                      '- Priority business need: Improve reporting quality, AI-safe drafting, meeting '
                                      'documentation, and action tracking within two months.'}],
 'Process Improvement Note': [{'title': 'Attached classroom-safe sample',
                               'text': 'Operational observations:\n'
                                       '- Current workflow: Department requests for data reports are submitted through '
                                       'email and manually assigned to analysts.\n'
                                       '- Average turnaround time: 6 working days; expected turnaround: 3 working '
                                       'days.\n'
                                       '- Nearly 30% of requests require clarification because the original email does '
                                       'not include date range, required format, or purpose.\n'
                                       '- Analysts maintain separate trackers, causing duplicate work when similar '
                                       'reports are requested by different departments.\n'
                                       '- Urgent requests are marked informally in email subject lines, but there is '
                                       'no agreed priority scale.\n'
                                       '- Department heads often escalate after four days because they cannot see '
                                       'request status.\n'
                                       '- Completed reports are stored in multiple folders with inconsistent naming '
                                       'conventions.\n'
                                       '- Staff do not want a paid workflow system at this stage.\n'
                                       '- Proposed improvement should be feasible using existing tools such as shared '
                                       'forms, Excel/Sheets trackers, and weekly review discipline.'}],
 'Budget Review Support': [{'title': 'Attached classroom-safe sample',
                            'text': 'Anonymised budget summary for Q3 review:\n'
                                    '\n'
                                    'Budget head | Annual allocation | Q1 spend | Q2 spend | Q3 spend | Notes\n'
                                    'Training programmes | 24.0 lakh | 4.5 lakh | 5.2 lakh | 9.8 lakh | Higher spend '
                                    'due to external faculty sessions\n'
                                    'Travel and field visits | 18.0 lakh | 3.1 lakh | 4.0 lakh | 6.7 lakh | Increase '
                                    'linked to regional review meetings\n'
                                    'Software subscriptions | 12.0 lakh | 2.8 lakh | 2.9 lakh | 4.6 lakh | Two '
                                    'renewals advanced from Q4\n'
                                    'Printing and materials | 5.0 lakh | 0.9 lakh | 1.1 lakh | 2.2 lakh | Workshop '
                                    'manuals printed in bulk\n'
                                    'Consultancy support | 15.0 lakh | 1.0 lakh | 3.5 lakh | 7.0 lakh | '
                                    'Milestone-based payment released\n'
                                    'Contingency | 4.0 lakh | 0.2 lakh | 0.3 lakh | 0.4 lakh | Low utilisation\n'
                                    '\n'
                                    'Review observations:\n'
                                    '- Total Q3 spend is 34% higher than Q2.\n'
                                    '- Two budget heads may exceed annual allocation if the Q3 pace continues.\n'
                                    '- Some Q3 expenses were timing-related rather than additional commitments.\n'
                                    '- Finance team needs questions for the budget-holder review meeting.'}],
 'Patient Communication Improvement': [{'title': 'Attached classroom-safe sample',
                                        'text': 'Draft patient communication template:\n'
                                                '\n'
                                                'Dear Patient,\n'
                                                'Your appointment has been scheduled. Please come to the hospital '
                                                'before the time mentioned. Carry the documents required for your '
                                                'visit. If you are late, your turn may be shifted. Payment and '
                                                'registration must be completed before consultation. Please cooperate '
                                                'with staff and wait for your number. For any issue, contact the help '
                                                'desk.\n'
                                                '\n'
                                                'Additional information to preserve:\n'
                                                '- Appointment date and time will be inserted separately by the '
                                                'hospital system.\n'
                                                '- Patients should bring appointment confirmation, previous reports if '
                                                'any, and valid identity proof.\n'
                                                '- Patients should not be asked to follow any clinical advice in this '
                                                'message.\n'
                                                '- The revised communication should be clear, respectful, and easy to '
                                                'understand.\n'
                                                '- Include a simple call to action and a note about arriving 20 '
                                                'minutes early for registration.'}],
 'Learning Programme Design': [{'title': 'Attached classroom-safe sample',
                                'text': 'Learning objectives:\n'
                                        '1. Explain what Generative AI can and cannot do in management work.\n'
                                        '2. Apply the R-C-T-O-F-E prompt framework to routine managerial tasks.\n'
                                        '3. Identify privacy, hallucination, and overreliance risks in AI-assisted '
                                        'outputs.\n'
                                        '4. Convert raw notes into a structured executive brief using safe sample '
                                        'data.\n'
                                        '5. Develop one personal action plan for responsible AI use at work.\n'
                                        '\n'
                                        'Topic outline:\n'
                                        '- Introduction to Generative AI for managers.\n'
                                        '- Differences between search, automation, analytics, and generative AI.\n'
                                        '- Prompt engineering basics: role, context, task, output, format, '
                                        'evaluation.\n'
                                        '- Executive use cases: meeting summaries, risk registers, stakeholder emails, '
                                        'dashboard narratives.\n'
                                        '- Responsible use: sensitive data, human review, verification checklist.\n'
                                        '- Hands-on activity: improve a weak prompt and test a strong prompt.\n'
                                        '\n'
                                        'Learner profile:\n'
                                        'Experienced managers with limited technical background. No coding expected.'}],
 'Supply Chain Risk Summary': [{'title': 'Attached classroom-safe sample',
                                'text': 'Supply chain observations:\n'
                                        '- Vendor A supplies 65% of critical packaging material and has reported a '
                                        '10-day production backlog.\n'
                                        '- Vendor B can provide substitute material but at 12% higher cost and with a '
                                        'minimum order quantity.\n'
                                        '- Average inbound transport time has increased from 4 days to 7 days due to '
                                        'regional route restrictions.\n'
                                        '- Warehouse inventory currently covers 13 days of normal demand; safety '
                                        'target is 21 days.\n'
                                        '- Demand is expected to rise by 18% during the next promotional cycle.\n'
                                        '- Quality team reported two minor packaging defects in the last batch from '
                                        'Vendor A.\n'
                                        '- Procurement has not finalised the alternate supplier onboarding checklist.\n'
                                        '- Operations team can adjust production sequencing for one week but not '
                                        'beyond that without affecting delivery commitments.\n'
                                        '- Leadership needs a concise risk summary with escalation triggers.'}],
 'Policy Simplification Note': [{'title': 'Attached classroom-safe sample',
                                 'text': 'Public policy extract for operational managers:\n'
                                         '\n'
                                         '1. Departments must maintain a documented approval trail for all externally '
                                         'funded training, consulting, or technology initiatives.\n'
                                         '2. Any expenditure above the delegated threshold must be reviewed by the '
                                         'finance office before commitment.\n'
                                         '3. Project owners must submit an implementation note covering purpose, '
                                         'expected benefit, responsible team, timeline, and risk controls.\n'
                                         '4. Personal or confidential data must not be shared with third-party tools '
                                         'unless authorised by the designated data protection authority.\n'
                                         '5. Project review meetings must record decisions, action owners, and '
                                         'unresolved clarification points.\n'
                                         '6. A post-implementation review must be completed within 60 days of project '
                                         'closure for initiatives above the reporting threshold.\n'
                                         '7. Where clauses are unclear, departments must seek formal clarification '
                                         'rather than relying on informal interpretation.'}],
 'Stakeholder Engagement Plan': [{'title': 'Attached classroom-safe sample',
                                  'text': 'Context: Implementation of a new digital reporting dashboard across '
                                          'departments.\n'
                                          '\n'
                                          'Stakeholder list:\n'
                                          '1. Senior leadership: Interested in concise monthly performance visibility; '
                                          'prefers dashboard summaries and exception alerts; monthly communication.\n'
                                          '2. Department heads: Interested in workload impact and report accuracy; '
                                          'prefer short review meetings and implementation notes; fortnightly '
                                          'communication during rollout.\n'
                                          '3. Reporting coordinators: Need hands-on training and clear templates; '
                                          'prefer workshops, FAQs, and helpdesk support; weekly communication in first '
                                          'month.\n'
                                          '4. IT support team: Responsible for access, technical troubleshooting, and '
                                          'user support; prefer ticket-based communication and issue logs; weekly '
                                          'coordination.\n'
                                          '5. Finance office: Needs alignment with budget and reporting compliance; '
                                          'prefers formal notes and review checkpoints; monthly updates.\n'
                                          '6. End users: Need simple instructions for data entry and interpretation; '
                                          'prefer short videos and one-page guides.\n'
                                          '\n'
                                          'Known concern: Some departments fear that dashboard transparency may be '
                                          'used for blame rather than improvement.'}],
 'Meeting Documentation': [{'title': 'Attached classroom-safe sample',
                            'text': 'Raw meeting notes:\n'
                                    '\n'
                                    'Meeting: Dashboard rollout coordination\n'
                                    'Date: 8 April 2026\n'
                                    'Participants: Project Lead, IT Support Lead, Department Coordinators, Finance '
                                    'Representative\n'
                                    '\n'
                                    'Discussion:\n'
                                    '- Project Lead said pilot dashboard will go live for three departments on 20 '
                                    'April.\n'
                                    '- IT Support Lead said user access list must be frozen by 12 April.\n'
                                    '- Two departments have not yet submitted final KPI definitions.\n'
                                    '- Finance Representative asked whether dashboard maintenance cost is already '
                                    'included in approved budget.\n'
                                    '- Coordinators requested a short training video before launch.\n'
                                    '- Project Lead agreed that dashboard colour codes should be explained in a '
                                    'one-page guide.\n'
                                    '\n'
                                    'Decisions:\n'
                                    '- Pilot launch date remains 20 April.\n'
                                    '- KPI definitions must be finalised before access setup.\n'
                                    '- A one-page guide will be prepared before launch.\n'
                                    '\n'
                                    'Action items:\n'
                                    '- Department Coordinators to submit KPI definitions by 10 April.\n'
                                    '- IT Support Lead to create user access list by 12 April.\n'
                                    '- Project Lead to circulate one-page guide by 16 April.\n'
                                    '- Finance Representative to confirm budget classification by 11 April.\n'
                                    '\n'
                                    'Pending issue:\n'
                                    '- No final decision on who will maintain the dashboard after the pilot.'}],
 'Performance Review Preparation': [{'title': 'Attached classroom-safe sample',
                                     'text': 'Performance observations for review preparation:\n'
                                             '- The employee coordinates monthly departmental reports and supports '
                                             'meeting documentation.\n'
                                             '- Strength: Timely submission of routine trackers in seven out of eight '
                                             'months.\n'
                                             '- Strength: Maintains courteous communication with multiple '
                                             'departments.\n'
                                             '- Strength: Helped reduce formatting inconsistencies in the monthly '
                                             'dashboard file.\n'
                                             '- Development area: Written summaries sometimes describe activities '
                                             'without identifying implications or next steps.\n'
                                             '- Development area: Needs to flag delays earlier instead of waiting for '
                                             'reminders.\n'
                                             '- Development area: Presentation updates are accurate but could be more '
                                             'concise.\n'
                                             '- Behavioural example: In the January review, the dashboard file was '
                                             'complete, but two variance explanations were missing.\n'
                                             '- Behavioural example: In March, the employee coordinated inputs from '
                                             'four departments and closed the report one day before deadline.\n'
                                             '- Suggested goal area: Structured executive summaries, proactive '
                                             'escalation, and data interpretation.\n'
                                             '- Do not include names, personal identifiers, or ratings.'}],
 'Executive Dashboard Narrative': [{'title': 'Attached classroom-safe sample',
                                    'text': 'Dashboard summary: Service performance dashboard, March 2026\n'
                                            '\n'
                                            'Key indicators:\n'
                                            '- Total service requests: 8,450; February: 7,980; change: +5.9%.\n'
                                            '- Closure rate: 92%; target: 94%; February: 91%.\n'
                                            '- Average resolution time: 39 hours; target: 36 hours; February: 42 '
                                            'hours.\n'
                                            '- Escalation rate: 9.8%; target: below 8%; February: 11.2%.\n'
                                            '- Customer satisfaction score: 4.1/5; target: 4.2/5; February: 4.0/5.\n'
                                            '- Digital ticket submission: 81%; target: 80%; February: 76%.\n'
                                            '- Pending requests older than 5 days: 312; February: 355.\n'
                                            '\n'
                                            'Highlights:\n'
                                            '- Digital adoption crossed target for the first time.\n'
                                            '- Resolution time and backlog improved compared with February.\n'
                                            '\n'
                                            'Concerns:\n'
                                            '- Closure rate remains below target despite improvement.\n'
                                            '- Escalation rate is still above tolerance.\n'
                                            '- Two regional teams account for 46% of requests older than 5 days.\n'
                                            '\n'
                                            'Leadership attention needed:\n'
                                            'Decide whether to extend support resources to the two high-backlog '
                                            'regions for April.'}]}

PROMPT_LIBRARY_SAMPLES = {'Executive Brief from Raw Notes': [{'title': 'Attached classroom-safe sample',
                                     'text': 'Administrative note: Improving Training Attendance and Reporting '
                                             'Efficiency\n'
                                             '\n'
                                             'Over the past two quarters, average attendance across scheduled internal '
                                             'training sessions has been 68%, against the desired level of 85%. '
                                             'Feedback collected from 47 participants indicates that the main reasons '
                                             'for non-attendance are scheduling conflicts, late communication of final '
                                             'dates, and uncertainty about whether sessions are mandatory or optional. '
                                             'Department coordinators also report that attendance data is currently '
                                             'compiled manually from multiple sign-in sheets, resulting in delays in '
                                             'sharing final reports with programme heads.\n'
                                             '\n'
                                             'Current practice:\n'
                                             '- Session invitations are sent by email 7-10 days before the programme.\n'
                                             '- Reminder emails are sent one day before the session.\n'
                                             '- Attendance is recorded manually and later transferred to Excel.\n'
                                             '- Programme heads receive consolidated reports 5-7 working days after '
                                             'session completion.\n'
                                             '\n'
                                             'Issues observed:\n'
                                             '- Some participants receive information through department heads rather '
                                             'than directly.\n'
                                             '- Rescheduling information is not always reflected in the final '
                                             'participant list.\n'
                                             '- Attendance reports do not consistently separate nominated, attended, '
                                             'absent, and exempted participants.\n'
                                             '\n'
                                             'Decision required:\n'
                                             'Programme leadership must decide whether to introduce a standard '
                                             'nomination tracker, a 48-hour confirmation rule, and a single reporting '
                                             'template for all training programmes.'}],
 'Risk Register Creation': [{'title': 'Attached classroom-safe sample',
                             'text': 'Project: Implementation of a no-cost AI-assisted report drafting workflow for '
                                     'administrative teams.\n'
                                     '\n'
                                     'Project objective:\n'
                                     'Help selected administrative staff use approved prompt templates to prepare '
                                     'first drafts of meeting summaries, executive briefs, and action trackers using '
                                     'only non-sensitive or dummy content.\n'
                                     '\n'
                                     'Scope:\n'
                                     '- Pilot with three departments for six weeks.\n'
                                     '- Provide prompt templates and verification checklists.\n'
                                     '- Collect feedback on time saved, output quality, and safety concerns.\n'
                                     '- No external data storage, paid tools, or confidential data sharing permitted.\n'
                                     '\n'
                                     'Known concerns:\n'
                                     '- Users may accidentally paste sensitive details into public AI tools.\n'
                                     '- Reviewers may trust AI outputs without checking facts.\n'
                                     '- Different departments may interpret safe-use rules differently.\n'
                                     '- Staff may resist adoption if they fear monitoring or job replacement.\n'
                                     '- Output quality may vary depending on prompt clarity.\n'
                                     '\n'
                                     'Governance requirement:\n'
                                     'All AI-assisted drafts must be reviewed by a responsible officer before '
                                     'circulation.'}],
 'Meeting Minutes from Raw Notes': [{'title': 'Attached classroom-safe sample',
                                     'text': 'Raw meeting notes:\n'
                                             '\n'
                                             'Meeting: AI report drafting pilot review\n'
                                             'Date: 18 February 2026\n'
                                             'Time: 11:00 AM-12:00 PM\n'
                                             'Attendees: Programme Head, Department Coordinator, IT Support '
                                             'Representative, Training Lead, Finance Representative\n'
                                             '\n'
                                             'Agenda:\n'
                                             '- Review readiness for pilot launch\n'
                                             '- Finalise departments for participation\n'
                                             '- Discuss data-safety checklist\n'
                                             '- Confirm training dates\n'
                                             '\n'
                                             'Discussion:\n'
                                             '- Programme Head suggested starting with three departments instead of '
                                             'five.\n'
                                             '- Training Lead said the first orientation can be completed in 90 '
                                             'minutes.\n'
                                             '- IT Support Representative clarified that no institutional system '
                                             'integration is planned at this stage.\n'
                                             '- Finance Representative asked whether any paid subscription is '
                                             'required; Training Lead confirmed no paid tool is required.\n'
                                             '- Department Coordinator requested a standard disclaimer for AI-assisted '
                                             'drafts.\n'
                                             '\n'
                                             'Decisions:\n'
                                             '- Pilot will start with three departments.\n'
                                             '- Orientation session will be held on 26 February.\n'
                                             '- Only synthetic, public, or approved sample data will be used.\n'
                                             '\n'
                                             'Actions:\n'
                                             '- Training Lead to share orientation agenda by 21 February.\n'
                                             '- Department Coordinator to collect participant names by 22 February.\n'
                                             '- IT Support Representative to prepare a one-page safe-use advisory by '
                                             '24 February.\n'
                                             '- Programme Head to approve the final disclaimer by 25 February.\n'
                                             '\n'
                                             'Pending:\n'
                                             '- Success metrics for pilot review need to be finalised.'}],
 'Stakeholder Communication Draft': [{'title': 'Attached classroom-safe sample',
                                      'text': 'Stakeholder group: Department heads and nominated staff participating '
                                              'in the AI-assisted reporting pilot.\n'
                                              '\n'
                                              'Context:\n'
                                              'The organisation is introducing a six-week pilot to help staff prepare '
                                              'first drafts of routine management documents such as meeting summaries, '
                                              'executive briefs, status updates, and risk notes. The pilot is designed '
                                              'for learning and productivity support, not for replacing human '
                                              'judgement or official approval.\n'
                                              '\n'
                                              'Key message:\n'
                                              'Participants will attend a 90-minute orientation and receive prompt '
                                              'templates, safe-use guidance, and a verification checklist.\n'
                                              '\n'
                                              'Action required:\n'
                                              'Department heads should nominate two staff members by 22 February 2026. '
                                              'Nominated staff should attend the orientation on 26 February 2026 and '
                                              'use only dummy, public, or approved non-sensitive content during '
                                              'practice.\n'
                                              '\n'
                                              'Timeline:\n'
                                              '- Nominations due: 22 February 2026\n'
                                              '- Orientation: 26 February 2026\n'
                                              '- Pilot period: 1 March-15 April 2026\n'
                                              '- Feedback submission: 18 April 2026\n'
                                              '\n'
                                              'Acknowledged concerns:\n'
                                              'Some staff may be unsure about privacy, workload, and whether AI output '
                                              'can be used directly. The communication should reassure them that human '
                                              'review remains mandatory and no confidential data should be entered '
                                              'into public tools.\n'
                                              '\n'
                                              'Contact for queries:\n'
                                              'Programme coordination office.'}],
 'Policy Simplification for Management': [{'title': 'Attached classroom-safe sample',
                                           'text': 'Public policy text:\n'
                                                   '\n'
                                                   'Digital Assistance and Data Responsibility Guidelines\n'
                                                   '\n'
                                                   '1. Staff may use digital assistance tools for drafting, '
                                                   'summarising, brainstorming, formatting, translation support, '
                                                   'training preparation, and other low-risk productivity tasks.\n'
                                                   '2. Staff must not submit confidential, personal, financial, '
                                                   'medical, legal, procurement-sensitive, disciplinary, unpublished, '
                                                   'or password-protected information to any public tool unless '
                                                   'written approval has been issued by the authorised office.\n'
                                                   '3. Outputs generated with digital assistance must be checked by '
                                                   'the responsible staff member before use. The staff member remains '
                                                   'accountable for factual accuracy, completeness, tone, and '
                                                   'compliance.\n'
                                                   '4. AI-assisted summaries of official policies, contracts, or '
                                                   'regulatory documents are not authoritative interpretations. Where '
                                                   'meaning is uncertain, formal clarification must be obtained.\n'
                                                   '5. Departments using AI assistance for recurring work should '
                                                   'maintain a list of approved use cases, verification steps, and '
                                                   'escalation contacts.\n'
                                                   '6. Any suspected data exposure or incorrect official communication '
                                                   'caused by AI-assisted drafting must be reported immediately to the '
                                                   'designated authority.\n'
                                                   '\n'
                                                   'Implementation date: 1 April 2026.\n'
                                                   'Applicability: All departments and contract staff handling '
                                                   'institutional information.'}],
 'Training Session Plan': [{'title': 'Attached classroom-safe sample',
                            'text': 'Learning objectives:\n'
                                    '- Define Generative AI in simple managerial terms.\n'
                                    '- Distinguish safe, low-risk AI uses from restricted or sensitive uses.\n'
                                    '- Apply a structured prompt framework to management communication tasks.\n'
                                    '- Convert raw notes into a concise executive brief.\n'
                                    '- Use a verification checklist before sharing AI-assisted outputs.\n'
                                    '\n'
                                    'Topic outline:\n'
                                    '1. What Generative AI is and how it differs from search engines.\n'
                                    '2. Common management use cases: summarisation, drafting, risk review, meeting '
                                    'documentation, stakeholder communication.\n'
                                    '3. R-C-T-O-F-E prompt framework: role, context, task, output, format, '
                                    'evaluation.\n'
                                    '4. Responsible AI principles: privacy, hallucination, bias, accountability, and '
                                    'human oversight.\n'
                                    '5. Hands-on activity: improve a weak prompt and create a management brief from '
                                    'safe sample data.\n'
                                    '6. Closing reflection: one use case participants can try safely in their own '
                                    'work.\n'
                                    '\n'
                                    'Audience:\n'
                                    'Experienced management professionals from mixed functional backgrounds.\n'
                                    '\n'
                                    'Constraints:\n'
                                    'No coding, no paid tools, no confidential data, and activities should work in a '
                                    'classroom with projector-based demonstration.'}],
 'Scenario Planning Note': [{'title': 'Attached classroom-safe sample',
                             'text': 'Management situation:\n'
                                     '\n'
                                     'A professional training institution plans to introduce AI-assisted drafting '
                                     'tools for internal programme administration. The expected benefits include '
                                     'faster executive briefs, cleaner meeting summaries, and better action tracking. '
                                     'However, staff experience with AI tools varies widely. Some staff are '
                                     'enthusiastic and already experimenting; others are concerned about data privacy, '
                                     'accuracy, and possible misuse.\n'
                                     '\n'
                                     'Current readiness:\n'
                                     '- Basic digital literacy is strong across departments.\n'
                                     '- No formal AI usage policy has yet been fully adopted.\n'
                                     '- Leadership supports innovation but wants clear safeguards.\n'
                                     '- IT support is available for basic tool guidance but not for custom software '
                                     'development.\n'
                                     '- Training time is limited because departments are managing several ongoing '
                                     'programmes.\n'
                                     '\n'
                                     'Decision horizon:\n'
                                     'Leadership wants a three-month phased implementation plan.\n'
                                     '\n'
                                     'Uncertainties:\n'
                                     '- Whether staff will follow safe-use rules consistently.\n'
                                     '- Whether AI-assisted drafts will actually reduce review burden.\n'
                                     '- Whether departments will standardise templates quickly.\n'
                                     '\n'
                                     'Need:\n'
                                     'Create optimistic, realistic, and risk-sensitive planning scenarios.'}],
 'Decision Memo with Options': [{'title': 'Attached classroom-safe sample',
                                 'text': 'Decision context:\n'
                                         'The programme office needs a better way to manage training attendance and '
                                         'reporting.\n'
                                         '\n'
                                         'Option A: Continue with the current email-based nomination and manual '
                                         'attendance process.\n'
                                         '- Cost: No additional financial cost.\n'
                                         '- Timeline: Immediate continuation.\n'
                                         '- Feasibility: High because all staff already know the process.\n'
                                         '- Risk: Continued delays, duplicate entries, and weak reporting '
                                         'consistency.\n'
                                         '- Stakeholder impact: Low disruption but continued frustration for '
                                         'coordinators.\n'
                                         '\n'
                                         'Option B: Introduce a shared spreadsheet tracker with standard fields and '
                                         'weekly review.\n'
                                         '- Cost: No paid software required.\n'
                                         '- Timeline: Can be implemented within two weeks.\n'
                                         '- Feasibility: Medium-high if departments follow naming and update rules.\n'
                                         '- Risk: Manual errors may continue, but visibility will improve.\n'
                                         '- Stakeholder impact: Moderate change for department coordinators.\n'
                                         '\n'
                                         'Option C: Use an online form linked to a central attendance dashboard.\n'
                                         '- Cost: No paid software if existing institutional tools are used.\n'
                                         '- Timeline: Four to six weeks for setup, testing, and orientation.\n'
                                         '- Feasibility: Medium; requires technical configuration and user training.\n'
                                         '- Risk: Adoption may be uneven in early weeks.\n'
                                         '- Stakeholder impact: Higher initial change but better long-term '
                                         'reporting.'}],
 'Procurement Justification Note': [{'title': 'Attached classroom-safe sample',
                                     'text': 'Non-sensitive procurement context:\n'
                                             '\n'
                                             'Requirement:\n'
                                             'The training office needs 40 reusable tablet stands and 4 wireless '
                                             'presentation clickers for classroom-based digital learning activities.\n'
                                             '\n'
                                             'Purpose:\n'
                                             'The items will support hands-on AI, dashboard, and polling activities '
                                             'during MDPs, FDPs, and student workshops. Participants often work in '
                                             'groups, and current classroom arrangements make it difficult for them to '
                                             'view shared devices comfortably.\n'
                                             '\n'
                                             'Estimated scope:\n'
                                             '- 40 foldable tablet stands suitable for classroom tables.\n'
                                             '- 4 wireless presentation clickers with standard USB receivers.\n'
                                             '- Basic storage box for safe keeping.\n'
                                             '\n'
                                             'Options considered:\n'
                                             '1. Continue without purchase: no cost, but repeated inconvenience during '
                                             'hands-on sessions.\n'
                                             '2. Borrow devices from different departments: uncertain availability and '
                                             'no single accountability.\n'
                                             '3. Procure a small reusable set: moderate one-time cost and predictable '
                                             'availability.\n'
                                             '\n'
                                             'Known risks:\n'
                                             '- Items may be misplaced without a checkout register.\n'
                                             '- Product quality may vary across vendors.\n'
                                             '- Compatibility should be checked before purchase.\n'
                                             '\n'
                                             'Missing information:\n'
                                             'Exact budget head, approved vendor list, warranty requirements, and '
                                             'institutional procurement thresholds.'}],
 'Performance Feedback Framework': [{'title': 'Attached classroom-safe sample',
                                     'text': 'Performance observations:\n'
                                             '\n'
                                             'Role context:\n'
                                             'The employee supports programme coordination, participant communication, '
                                             'and post-session documentation.\n'
                                             '\n'
                                             'Strengths:\n'
                                             '- Sends programme reminders on schedule.\n'
                                             '- Maintains a respectful communication style with faculty and '
                                             'participants.\n'
                                             '- Created a simple checklist that reduced missing pre-session '
                                             'materials.\n'
                                             '- Assisted colleagues during two high-volume programme weeks.\n'
                                             '- Learns new digital tools quickly when given structured guidance.\n'
                                             '\n'
                                             'Development priorities:\n'
                                             '- Needs to improve accuracy in consolidated attendance sheets.\n'
                                             '- Should separate confirmed information from pending information in '
                                             'status updates.\n'
                                             '- Needs to flag scheduling conflicts earlier.\n'
                                             '- Could make programme closure reports more analytical by including key '
                                             'observations and follow-up points.\n'
                                             '\n'
                                             'Examples:\n'
                                             '- In the February programme, the communication was timely, but two '
                                             'participant substitutions were not reflected in the final sheet.\n'
                                             '- In the March programme, the checklist was used effectively and reduced '
                                             'last-minute coordination calls.\n'
                                             '- In one review meeting, the employee provided a detailed update but did '
                                             'not clearly identify decisions required from the programme head.\n'
                                             '\n'
                                             'Goal direction:\n'
                                             'Improve data accuracy, structured reporting, and proactive escalation '
                                             'over the next review cycle.'}],
 'Data Storytelling Summary': [{'title': 'Attached classroom-safe sample',
                                'text': 'Management data observations:\n'
                                        '\n'
                                        'Training attendance dashboard for Q3 FY2025-26:\n'
                                        '- Total sessions conducted: 18\n'
                                        '- Average attendance: 72%; target: 85%\n'
                                        '- Attendance for mandatory sessions: 81%\n'
                                        '- Attendance for optional sessions: 58%\n'
                                        '- Average feedback score: 4.2/5\n'
                                        '- Percentage of participants requesting more hands-on time: 46%\n'
                                        '- Percentage of participants requesting shorter sessions: 22%\n'
                                        '- Number of departments with attendance below 60%: 3\n'
                                        '- Average delay in sharing attendance reports: 5 working days\n'
                                        '\n'
                                        'Additional observations:\n'
                                        '- Sessions scheduled after 4 PM had lower attendance than morning sessions.\n'
                                        '- Attendance was higher when department heads sent reminders directly.\n'
                                        '- Feedback quality was positive even when attendance was below target.\n'
                                        '- Programme team believes reporting delay is caused by manual consolidation.\n'
                                        '\n'
                                        'Need:\n'
                                        'Create a senior-leadership narrative that does not overstate causality.'}],
 'AI Adoption Communication': [{'title': 'Attached classroom-safe sample',
                                'text': 'AI adoption context:\n'
                                        '\n'
                                        'The department is introducing AI-assisted drafting as a support tool for '
                                        'routine administrative and management communication. The initial use cases '
                                        'include meeting summaries, executive brief drafts, stakeholder email drafts, '
                                        'training outlines, and risk note templates.\n'
                                        '\n'
                                        'Purpose:\n'
                                        'Reduce time spent on first-draft preparation and improve structure, clarity, '
                                        'and consistency.\n'
                                        '\n'
                                        'What AI will support:\n'
                                        '- Drafting from approved notes.\n'
                                        '- Summarising non-sensitive material.\n'
                                        '- Creating structured templates.\n'
                                        '- Improving tone and clarity.\n'
                                        '- Generating checklists and reflection questions.\n'
                                        '\n'
                                        'What AI will not replace:\n'
                                        '- Human judgement.\n'
                                        '- Official approval.\n'
                                        '- Policy interpretation.\n'
                                        '- Confidential decision-making.\n'
                                        '- Accountability for final communication.\n'
                                        '\n'
                                        'Safety rules:\n'
                                        '- Do not paste confidential, personal, financial, legal, medical, '
                                        'disciplinary, or procurement-sensitive information into public tools.\n'
                                        '- Verify all facts before sharing.\n'
                                        '- Mark uncertain points clearly.\n'
                                        '- Use AI output as a draft, not a final decision.\n'
                                        '\n'
                                        'Concern to address:\n'
                                        'Some team members worry that AI will increase monitoring or reduce the value '
                                        'of human expertise.'}],
 'Briefing Note for Leadership': [{'title': 'Attached classroom-safe sample',
                                   'text': 'Topic/source for leadership briefing:\n'
                                           '\n'
                                           'Subject: Introducing a standard verification checklist for AI-assisted '
                                           'management drafts.\n'
                                           '\n'
                                           'Background:\n'
                                           'Several departments have begun experimenting with free AI tools for '
                                           'drafting reports, meeting notes, communication templates, and training '
                                           'material. While these tools can improve speed and structure, there is '
                                           'currently no common verification practice before AI-assisted drafts are '
                                           'shared internally.\n'
                                           '\n'
                                           'Current status:\n'
                                           '- Staff awareness of AI tools is increasing.\n'
                                           '- Some teams already use AI informally for summarisation and drafting.\n'
                                           '- No major incident has been reported, but reviewers have noticed '
                                           'unsupported claims in a few draft summaries.\n'
                                           '- Departments differ in how they label AI-assisted content.\n'
                                           '- Programme leadership wants a practical safeguard that does not '
                                           'discourage responsible innovation.\n'
                                           '\n'
                                           'Decision required:\n'
                                           'Approve whether a five-point verification checklist should be used for all '
                                           'AI-assisted drafts before internal circulation.\n'
                                           '\n'
                                           'Possible checklist items:\n'
                                           '1. Confirm that no sensitive data was entered.\n'
                                           '2. Verify all facts, figures, names, and dates.\n'
                                           '3. Check tone and institutional appropriateness.\n'
                                           '4. Mark assumptions and uncertainties.\n'
                                           '5. Ensure responsible officer review before circulation.\n'
                                           '\n'
                                           'Options:\n'
                                           '- Option 1: Issue checklist as advisory guidance.\n'
                                           '- Option 2: Make checklist mandatory for all departments.\n'
                                           '- Option 3: Pilot checklist in three departments before wider rollout.'}]}

